anuket-project/anuket-specifications

README.md
logistics/README.md

Update Front Page

---

doc/ref_model/chapters/chapter04.md

Addressing Comments form @hdamker, @ASawwaf, @TommyKTheDJ
Issue: https://github.com/cntt-n/CNTT/issues/32

Chapter 04 (based on comments (Re Issue# 32)) 

---

doc/ref_model/chapters/chapter05.md

Modifications on introduction, 5.1, 5.2 and 5.3

Chapter 05 (5.1,5.2,5.3)

---

doc/ref_model/chapters/chapter01.md

Chapter 01 (1.6)

---

doc/ref_model/chapters/chapter01.md

Chapter 01 (Principles) 

---

logistics/README.md

Introducing Automatic Approval process and contribution guidelines.

Logistics Update

---

doc/ref_model/chapters/chapter01.md

Removed Figures as agreed in meeting

Chapter 1.0 (Remove Figures form Terminology)

---

logistics/README.md

Fix for Issue: https://github.com/cntt-n/CNTT/issues/49

Fix for Issue: https://github.com/cntt-n/CNTT/issues/49

---

doc/ref_model/chapters/chapter01.md

Chap 1 mechanical fix

---

doc/ref_model/chapters/chapter01.md

Changes to Chapter 1.4: Principles

Update Chapter 01.md

---

doc/ref_model/chapters/chapter03.md

A few comments are included to explain proposed changes

Update chap 3 - metrics sections

---

doc/ref_model/chapters/chapter05.md

Chapter 5: alignment with chapter 4

---

doc/ref_model/chapters/chapter04.md

New Pull Request for Chapter03

Chapter 3( minor change)

---

doc/ref_model/chapters/chapter05.md

Addition of definitions for tables 5-1 and 5-5

update Chapter 05: definitions in Tables

---

doc/ref_model/chapters/chapter08.md

Could not figure out how to do it from my branch, so did it from the master.

Updated Chapter08.MD with all the comments and changes

---

doc/ref_arch/chapters/chapter03.md

Fixing numbering in chapter 3

---

doc/ref_model/chapters/chapter05.md

move hw profile section introduction from the end of 5.2 to the beginning of 5.3
(only for the sake of clarity before reworking the whole chapter)

Chapter05 - hw profile section introduction moving

---

doc/ref_model/chapters/chapter03.md

#201 Clarify the intention of the design principle: Declarative

[Reference Model] Chapter 3 - Clarify design principle: Declarative

---

doc/ref_model/chapters/chapter01.md
doc/ref_model/chapters/chapter03.md

Tenant definition focuses on the pooling of resources provided by the NFVI and not on any organisational structures and roles.

Chapter 1 -  tenant definition

---

doc/ref_model/chapters/chapter05.md

5.1 Introduction, modification referring to issue #140 
5.1.1 and 5.2.1, "support of flavours" removed referring to issue #145 
5.1.3 and 5.2.3, "Horizontal scaling" replaced by " NFVI scaling"

Chapter 5 - Sections 5.1 and 5.2

---

doc/ref_model/chapters/chapter04.md

Proposition of a first set of capabilities for VIM

WIP: [RM] Chapter 4 section 4.1.6 VIM capabilities

---

doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md

This PR will contain outline proposal for Chapter 4 (Level 3 artefacts). The content of Chapter 4 will go down to component level.

[Reference Architecture] Ch 03 + Ch 04 outlines

---

doc/ref_model/chapters/chapter07.md

Modification of the title "NFVI and VIM Vendors responsibility"
Addition of §7.10.4

[Reference Model] Chapter 7 - 7.10 addition of VIM

---

doc/ref_model/chapters/chapter08.md

Issue 273 - [Rm Ch8]: Annex for Chapter 8 link is incorrect #273.
Fixed.  Broke after PR.  Corrected.  Closed.

[RM Chapter 8] Updates - Content and Issues

---

_config.yml

It fixes all errors detected by yamllint [1]
[1] https://github.com/adrienverge/yamllint

Fix 2 errors in _config.yml

---

doc/ref_arch/openstack/chapters/chapter02.md

Issue #297 Corrected req.gen.rsl.02 and req.lcm.adp.01.

Upadte Chapter 02.md

---

doc/ref_model/chapters/chapter05.md

Editorial changes: English GB spelling for virtualisation, optimisation, use and used

[RM Chapter 5] English US -> English GB

---

doc/ref_model/chapters/chapter05.md

Table 5.13: BIOS removed from NUMA description -> #issue296

[RM Chapter 5] HW profile, BIOS reference removed from NUMA description

---

doc/ref_arch/openstack/chapters/chapter05.md

[RA Ch05] Update Chpater05.md

---

doc/ref_model/chapters/chapter04.md

[RM Chapter 4] Resolves Paris F/B JB-3

---

doc/ref_model/chapters/chapter10.md

Moving @jbeltranatl Pull Request to use the right file.
Replacement for https://github.com/cntt-n/CNTT/pull/292

[RM Ch10] Update chapter10.md

---

doc/ref_model/chapters/chapter04.md

[RM CH 4] Update 1 Stop Shop (4.3)

---

doc/ref_model/chapters/chapter04.md

...during Botrange cleanup/merge.

[RM Chapter 4] Re-Inserts Paragraph Accidently Deleted

---

doc/ref_arch/openstack/chapters/chapter05.md

Issue #371 
Modified "Baseline" to "Minimum (Baseline)" for the version Information

Update RA-1 Chapter05 APIs

---

doc/ref_model/chapters/chapter04.md

This commit addresses Issue #377, replacing the term metric w/ measurement (see Issue for details), as well as some mechanical cleanup.

[RM Ch04] Resolve Issues 377, 380 & 381

---

doc/gov/chapters/chapter02.md

Rabi - my first pull requests! Yay! Now tell me what I did wrong if anything.

[CSO Ch02 - Gov] Initialized chapter name

---

doc/ref_arch/kubernetes/chapters/chapter03.md
doc/ref_arch/kubernetes/chapters/chapter04.md

This change contains an open ended proposal for the structure of
Ch3 and Ch4.

[RA2 Core]: ToC proposal for Ch3 and Ch4

---

doc/ref_arch/openstack/chapters/chapter04.md

Issue #440 Update content in Overview with reference to Reference Model (RM) Section 3.3 Management Software and modified table to include mapping between RM management functions and the core OpenStack Services.

[RA-1 Ch4] Section 4.3.2. Overview

---

doc/ref_model/chapters/appendix-a.md

Resolving issue: https://github.com/cntt-n/CNTT/issues/294

[RM Core Appendix A] Initial structure

---

doc/ref_model/chapters/chapter01.md

This change defines what are standars and open API-s in the princinples
of the Reference Model.
Fixes #424

[RM Ch1] Definition of standard and open API-s

---

doc/ref_model/chapters/chapter07.md

* Fixed table numbers - https://github.com/cntt-n/CNTT/issues/396

[RM Ch07] Typo Corrections in Sect. 7.10.5

---

doc/gov/chapters/chapter02.md

JUN-1 TEST Patch integration wJira

JUN-1 TEST 2 TEST PR FOR JIRA GITHUB integration

---

doc/ref_arch/kubernetes/chapters/chapter01.md

[RA2 Ch01] Added note as per issue #454

---

doc/ref_model/chapters/chapter04.md

- Integrate New PM/Cap Identifier Schema // Issue #390
- Remove PMs relocated to RCx/RMCH-8 // Issue #378
- Add draft definitions in support of schema // currently commented out
- Mechanical and typo cleanup

[RM Ch04] Integrate New PM/Cap Identifier Schema +

---

doc/gov/chapters/chapter01.md

Added text to create a rough draft.

[Gov Ch01] Rough draft of intro.

---

doc/ref_model/chapters/chapter08.md

This adds a list of requirements test cases and tools must meet to be
eligable for inclusion in the compliance program.
Closes #470

[RM Ch08] List of requirements for guiding test case selection

---

doc/ref_arch/openstack/chapters/chapter07.md

Resolving issue #369 
Proposal of ToC and outline to start "Operations and LCM" chapter

[RA1 Ch07] ToC and first outline for Chapter 7

---

doc/ref_arch/kubernetes/chapters/chapter08.md

[RA2 Ch08] Outline for Gaps & Development

---

doc/ref_arch/kubernetes/chapters/chapter03.md
doc/ref_arch/kubernetes/chapters/chapter04.md

This change adds discussion about the selection of container package managers
and a recommendation for Helm v3.
Fixes #451

[RA2 Ch03 Ch04] Adding container package manager

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Issue #445 -- Create initial set of requirements

[RA-2 Ch02] Requirements

---

doc/ref_impl/cntt-ri/chapters/chapter01.md

I modify this chapter to include more details. However I have trouble seeing the two figures, so not sure what is actually there. Can anyone help adding more details about what is indicated in those figures.

[RI 1 Core] Update Chp 01 for RI

---

.gitignore
doc/ref_arch/openstack/chapters/chapter05.md

* remove version specification from the standard service version
Fixes: #561

[RA1 CH05] Remove version specification [Fixes #561]

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA-1 CH03] Initial Content -- Issue #323
Content from @iangardner22 @karinesevilla @samuelhellec and @pgoyal01

[RA-1 CH03] Initial Content

---

doc/gov/chapters/chapter02.md

initial chapter 2 framework only

CCSO-10 added cso chapter 2 framework

---

.github/labeler.yml
.github/workflows/label.yml

[Technical Steering] Create label.yml

---

doc/gov/chapters/chapter04.md

to start wroking on #489 #490 #491 #492 #493 #494 #496 #497 #498 #504

[Gov Ch04] Nomination and Selection

---

doc/ref_model/chapters/chapter01.md

[RM Ch01] Fix hyperlink for terminology in RM chapter 01

---

doc/ref_cert/lfn/chapters/chapter04.md

Draft content for traceability matrix.
[Fixes #412 ]

[RC Ch04] Draft content for traceability matrix.

---

doc/ref_arch/openstack/chapters/chapter05.md

It sets the minimal microversion and the mandatory Nova features which
precises the API available.
Fixes #659

[RA1 Ch05] Update Nova API

---

doc/ref_impl/cntt-ri/chapters/chapter07.md

Initial content and placeholders for contributor edits to Ch 7 for the Run-Book.
Solves: #408

[RI1 Ch07] User Manual initial content

---

doc/ref_arch/kubernetes/chapters/chapter03.md

This change contains some clarifications to the ToC part of
RA2 Ch3.

[RA2 Ch3] Clarification of the compute part of RA2 Ch3 ToC

---

doc/ref_model/chapters/chapter05.md

[RM Ch5] Correction of header anchors

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

a draft version to 
Fixes #402

[RI1 Ch03] Add the Initial draft

---

CODEOWNERS
CONTRIBUTING.md

[Technical Steering] Update Contribution Process

---

doc/ref_model/chapters/chapter01.md

figure 1.6 -> 1.1
figure 1.4 -> 1.2
figure 1.5 -> 1.3
figure 1.7 -> 1.4

[RM Ch01] Corrected Figure Numbering per Issue #382

---

doc/ref_model/chapters/chapter05.md

[Rm Ch05] Resolve S/W Profile and Instance Type Usage

---

doc/ref_model/chapters/chapter05.md

[RM Ch05] Remove Confusion about SR-IOV.

---

doc/gov/README.md

CCSO-2 Chapter title updates (minor update only)

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 Ch04] Changed Title of 4.3 to Virtualised Infrastructure Manager. Fixes #718

[RA-1 Ch04] Changed Title of 4.3

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA-1 Ch03] Change Title for 3.3 to Virtualised Infrastructure Manager. Fixes #717

[RA-1 Ch03] Change Title for 3.3

---

doc/ref_cert/lfn/chapters/chapter04.md

PR generated for leads to expand and:
- Define RM/RA-1 Openstack requirements
- Map Framework/TestCases to Requirements
Leads will update/add content:  Rajesh, Dan, Ashok

RC1 Ch04 - Revised Draft

---

doc/ref_cert/lfn/chapters/chapter06.md

Add initial content of VNF test case requirements, please help to review. Thanks

[RC1 Ch06] VNF Test Case Requirements

---

doc/ref_cert/lfn/README.md
doc/ref_cert/lfn/chapters/chapter05.md

Removes dublicate scope diagram
Fix minor spell mistake

[RC-Ch05] Issue #751: Minor bug fixes

---

doc/ref_model/chapters/chapter01.md

Fixes issue #746 (Proposed language)

[RM Ch01] Adds H/W Abstraction Related Principles and Hooks (1 of 3)

---

doc/ref_model/chapters/chapter04.md

Adds references to applicable CNTT Principles and supporting Policies.
Fixes #746.
This is 2 of 3 PRs, as the webUI doesn't seem to allow additional files to be added to the same PR...

[RM Ch04] Insert H/W-dependent Capability References (2 of 3)

---

doc/ref_model/chapters/appendix-a.md

[RM Ch-A] Hardware Coding Policy Initial Framework (3 of 3)

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA 1 Ch03] Add content for Flavor Management in Section 3.3.4

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 CH04] 4.2.3.3. Octavia v2 API compliant Load Balancing
Fixes #725

[RA-1 CH04] 4.2.3.3. Load Balancing

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA-1 Ch03] 3.2.5 Virtual Networking – 3rd party SDN solution
Fixes #633

[RA-1 Ch03] 3.2.5 SDN

---

doc/ref_model/chapters/glossary.md

[RM Glossary] Added Cloud User (ITU), Tenant (ITU; made existing a Note), and Multi-tenancy (ETSI) per discussion in Issue #666.

[RM Glossary] Cloud User, Tenant, Multi-tenancy

---

doc/ref_impl/cntt-ri/chapters/chapter05.md

This is a draft commit for the installer requirement for the issue #404 where I try to describe the installer requirements and descriptor file definition.
Welcome any comments and discussion from community.
adding @mf4716 @fuqiao123

[RI1 Ch05] draft the first commit for installer requirement

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Added new wording for these requirements.
Fixes #607 
Fixes #606 
@fzdarsky does this wording work for you?  I can't add you as a reviewer for some reason.

[RA2 Ch2] req.inf.vir.01 & req.inf.phy.01

---

doc/ref_cert/lfn/chapters/chapter03.md

Updated initial draft. Leads will take it forward: Georg, Toshi, Deepanshu
New ToC entries:
	Assumptions:  Automatable, Integrated with CICD tool chain
	Type of requirement:  Bare metal, API, etc
	Table showing Profile Catalog
	Identify SW Reference
	Identify HW Reference
	Options Available / Configured
	Extensions Available / Configured

RC1 Ch03 - Updated ToC and Draft

---

doc/ref_cert/lfn/chapters/chapter11.md

Started initial draft. Leads will take it forward: Cedric, Kanagaraj, Shiby (confirmed) 
Content to include, but not limited to:
	Test Case Gaps (analysis)
	Automation Gaps
	Open Stack release Comparisons (Ocata, Pike, Queens, Stein, etc)
- Framework Gaps

RC1 Ch11 - Initial ToC and Draft

---

doc/ref_cert/lfn/chapters/chapter02.md

Started initial draft.  Leads will take it forward:  Cedric, Manik (confirmed)
	Methodology
	Certification Strategy & Vehicle
	Profiles Reference 
	Compliance, Verification, and Certification
	Entry & Exit Criteria
	Framework requirements

RC1 Ch02 - Initial ToC and Draft

---

doc/ref_cert/lfn/chapters/chapter07.md

Started initial ToC draft. Leads will take it forward:  Rajesh, Kanagaraj, Yan Yang (confirmed)
	Define RM/RA-1 Openstack requirements
	Map Framework to Requirements

RC1 Ch07 - Initial ToC and Draft

---

doc/ref_cert/lfn/chapters/chapter09.md

Started initial draft. Leads will take it forward:  Cedric
To include, but not limited to:
	Define RM/RA-1 Openstack requirements
	Map Framework to Requirements

RC1 Ch09 - Initial ToC and Draft

---

doc/ref_cert/lfn/chapters/chapter10.md

Started initial draft. Leads will take it forward: Cedric, Liping, Shilby
To include, but not limited to the following sections:
	Define RM/RA-1 Openstack requirements
	Map Framework to Requirements

RC1 Ch10 - Initial ToC and Draft

---

doc/ref_arch/openstack/chapters/chapter02.md

* Fix sub-headings
* Remove "." from table names and headings
Fixes #772

[RA1 Ch02]: Fix Chapter 2 TOC

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2 Ch02]: Fix Chapter 2 TOC

---

doc/ref_arch/openstack/chapters/chapter06.md

First input, issue #455
Fixes #455

[RA1 Ch06] ToC proposal

---

doc/ref_cert/lfn/chapters/chapter04.md

* Add section outline
* fix typos
* fix broken tables
Fixes Issue#780

[RC1 Ch04] Add section outline for test cases in interface and APIs

---

doc/gov/chapters/chapter02.md

Modified language to address participation not membership in CNTT.

CCSO-10 Change membership to participate WIP update.

---

doc/gov/chapters/chapter03.md

[Gov CSO] New WS Policy

---

doc/ref_cert/lfn/chapters/chapter05.md

Describe additional details for each requirements in the platform

[RC ch05] Add more details into VNF platform requirements

---

doc/ref_arch/openstack/chapters/chapter05.md

Fixes #814
Bogo-meter rating changed from "Initial framework" to"Dickering over the fine points"

[RA1 Ch05] Bogo meter rating changed

---

doc/gov/chapters/chapter05.md

Fixes #495 
Fixes #499 
Fixes #500 
Fixes #501 
Fixes #502 
Fixes #503 
Fixes #505 
Fixes #776

[Gov Ch05] Voting and approvals

---

doc/ref_cert/lfn/chapters/chapter05.md

[RC1] [Ch 5] Section 5.3.11 Updated gRPC -> RPC

---

doc/ref_arch/openstack/chapters/chapter08.md

Fixing the original commit to put it under appropriate header (i.e Section 8.2)
This addresses issue number 372

[RA1 Ch08] Update chapter08.md

---

doc/ref_model/chapters/glossary.md

[RM Glossary] Fix some container related definitions

---

doc/ref_model/chapters/glossary.md

[RM Glossary] Platform definition
Fixes #741

[RM Glossary] Platform definition

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Heat testing in RC1 4.3.4.7.
Closes: #834

[RC1] Fill Heat testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Keystone testing in RC1 4.3.4.1.
Closes: #830

[RC1] Fill Keystone testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Swift testing in RC1 4.3.4.4.
Closes: #838

[RC1] Fill Swift testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Nova testing in RC1 4.3.4.6.
Closes: #841

[RC1] Fill Nova testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Neutron testing in RC1 4.3.4.5.
Closes: #840

[RC1] Fill Neutron testing

---

doc/ref_cert/lfn/chapters/chapter09.md

It lists the testcases already executed in NFVI Compliance
https://lists.opnfv.org/g/opnfv-tsc/message/5717
It also maps them to the requirements being written in
[RC1] Chapter 4.
Then it's linked to the next PRs:
- https://github.com/cntt-n/CNTT/pull/831
- https://github.com/cntt-n/CNTT/pull/833
- https://github.com/cntt-n/CNTT/pull/835
- https://github.com/cntt-n/CNTT/pull/837
- https://github.com/cntt-n/CNTT/pull/839
- https://github.com/cntt-n/CNTT/pull/844
- https://github.com/cntt-n/CNTT/pull/845
- https://github.com/cntt-n/CNTT/pull/848
- https://github.com/cntt-n/CNTT/pull/853

[RC1] List CNTT mandatory testcases for compliance/certification

---

doc/ref_cert/lfn/chapters/chapter04.md

It fills 4.3.4 Interfaces & APIs.
Fixes: #859

[RC1] Introduce API testing

---

doc/ref_arch/openstack/chapters/chapter05.md

It adds Placement API and standardizes the tabs.
It also adds a few optional capabilities/extensions:
- tag-ext in neutron extension
- cert (or nova_cert) in Nova capabilities
- multi_backend in Cinder capabilities
Fixes: #861

[RA1 Ch05] Finalize API versions and capabilities

---

doc/ref_cert/lfn/chapters/chapter06.md

Update chapter06, add the test case list and update some other content, please help review

[RC Ch06] Update chapter06.md

---

doc/ref_arch/kubernetes/chapters/chapter05.md

RA2 ch5 Initial ToC

---

doc/ref_cert/lfn/chapters/chapter02.md

Xtesting and Xtesting CI meet the CNTT requirements about
verification, compliance and certification:
- smoothly assemble multiple heterogeneous test cases
- generate the Jenkins jobs in OPNFV Releng to verify CNTT RI
- deploy local CI/CD toolchains everywhere to check compliance with CNTT
- dump all test case results and logs for third-party certification review
The CI/CD approach (methodology) will be detailed in additional PRs.
Fixes: #866

[RC1] Define the frameworks for NFVI certification

---

doc/ref_cert/lfn/chapters/chapter01.md
doc/ref_cert/lfn/chapters/chapter04.md
doc/ref_cert/lfn/chapters/chapter09.md

Co-Authored-By: Pankaj Goyal <pg683k@att.com>

[RC1] Fix typos and replace next by following (nit)

---

doc/ref_impl/cntt-ri/chapters/chapter01.md
doc/ref_impl/cntt-ri/chapters/chapter05.md

[RI1] Typos (nit)

---

doc/ref_model/chapters/chapter04.md

Fixes #588 
Refer to Issue #588 for rationale and discussion supporting this PR.

[RM Ch04] Update/Refine Storage Extensions

---

doc/ref_cert/lfn/chapters/chapter03.md

[RC1 Ch03] - NFVI test case requirements

---

doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md

Add acceleration support to 3.2.6 Acceleration
Add cyborg to 3.3.1.3 Cloud Controller Services
Add cyborg to 4.3.1 VIM Core Services
Fixes #368

[RA-1 Ch03] Add acceleration support

---

doc/ref_model/chapters/glossary.md

[RM Glossary] Add SMT definition

---

doc/ref_arch/openstack/chapters/chapter02.md

[RA-1 Ch02] Bogo Meter Update to "Dickering"
Fixes #902

[RA-1 Ch02] Bogo Meter Update

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA-1 Ch03] Bogo Meter update to "Dickering"
Fixes #903

[RA-1 Ch03] Bogo Meter update to "Dickering"

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 Ch04] Change Bogo Meter to "Still Developing Content"
Fixes #904

[RA-1 Ch04] Change Bogo Meter to "SDC"

---

doc/ref_arch/kubernetes/chapters/chapter07.md

RA2 Ch7 ToC

---

doc/ref_arch/openstack/chapters/chapter08.md

Just cleaned up the wording based upon feedback
Fixes #914

Cleaning up the wording

---

doc/ref_arch/kubernetes/chapters/chapter06.md

Continue update chapter 6 based on latest discussion

[RA2 Ch06] Update chapter06.md

---

doc/ref_arch/kubernetes/chapters/chapter03.md

RA2 Ch3 - change status

---

doc/ref_arch/kubernetes/chapters/chapter06.md

RA2 Ch6 - update status

---

doc/ref_arch/kubernetes/chapters/chapter08.md

RA2 Ch8 - update status

---

.github/labeler.yml

Auto-labelling for RM/RA1/RA2 readme files.

labeler.yml - added some README.md files

---

doc/ref_cert/lfn/chapters/chapter11.md

[RC] One missing word (nit)

---

doc/ref_impl/cntt-ri/chapters/chapter07.md

It fixes the last side effect created by [1] which should have been
rebased prior to merge.
[1] https://github.com/cntt-n/CNTT/commit/3c365155f7062da8a0150b1d8b819a763bb801d0

[RI] Fix Release (last minute merge)

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Adding in the line about conformant K8s address #601

[RA2 Ch02] adding conformant k8s as a requirement

---

doc/ref_model/chapters/chapter04.md

fixing minor spelling and formatting mistakes

[RM Ch04] Fixing minor editorial issues

---

doc/ref_arch/openstack/chapters/chapter02.md

[RA-1 Ch02] Added Traceability Column: will be filled with references to where in the document requirement is addressed.
Fixes Issue #952

[RA-1 Ch02] Added Traceability Column

---

doc/gov/chapters/chapter04.md

For **Typos and spelling mistakes**, please EDIT the PR directly
For any **other comment**, please provide a "Review Request" 
Fixes #489
Fixes #490 
Fixes #491 
Fixes #492 
Fixes #493 
Fixes #494 
Fixes #496 
Fixes #497 
Fixes #498 
Fixes #504

[Gov Ch04] Nomination and Selection Process

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3]: Fixing links in RA2 Ch3

---

doc/ref_arch/openstack/chapters/chapter05.md

Added Cyborg (Accelerator) APIs reference.
Fixes Issue #825

[Ra-1 Ch05] Add Cyborg APIs

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2 Ch02] Add support for dual stack IPv4 and IPv6

---

doc/ref_arch/openstack/chapters/chapter05.md

Fixes #1005 
Text added in the introduction 5.1

[RA1 Ch 05] Explanations about API versions and microversions

---

doc/ref_impl/cntt-ri/chapters/chapter05.md

Hello, this is drafted hardware delivery verfication(HDV) requirement content open for review.
The original location is [https://wiki.lfnetworking.org/pages/viewpage.action?pageId=27525908](CNTT Hardware Delivery Validation (01-2020 DDF))

[RI-NewChp05] first commit for hardware delivery verification

---

doc/ref_arch/openstack/chapters/chapter03.md

Fixes #1085 
Removed sentence with MVP in section 3.1.

[RA-1 Ch03] Corrections

---

doc/ref_arch/openstack/chapters/chapter04.md

Fixes #1054 
Added 4.3.1.11 Placement Service
Modified 4.3.1 so as to reflect that more than the core services are being described.

[RA-1 Ch04] Add Placement Service

---

doc/ref_cert/lfn/chapters/chapter03.md

[RC Ch3] Add TST009 benchmarking to the Dataplane section

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Agreed in #603 that this should be removed.

[RA2 Core] Remove commented requirement

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] remove redundant note

---

doc/ref_arch/kubernetes/chapters/chapter01.md

This change mpoints ot the concrete repo of Kubernetes.

[RA2 Ch01]: Clarification of the location of Kubernetes

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] Remove 3.3

---

doc/ref_model/chapters/chapter01.md

This material applies to Issue 1037, and is intended to kick off content generation for Baldy.

[RM Ch1] Draft Networking language for Baldy

---

doc/ref_arch/openstack/chapters/chapter03.md

Corrections:
- 3.2.3 line breaks missing
- 3.3.1 NFVi -> NFVI
- 3.3.1.2, line break missing
- 3.3.1.4 drives -> drivers

[RA1 Ch03] Minor corrections: typos, line breaks

---

doc/ref_model/chapters/chapter01.md

[RM Ch01]: Removal of note about VM only scope of the RM

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2 Ch02]: Changing req.kcm.09 from should to must

---

doc/ref_arch/kubernetes/chapters/chapter02.md

remove compute-intensive from General req.

[RA2 Ch02] Update chapter02.md

---

doc/ref_arch/kubernetes/chapters/chapter02.md

req.inf.ntw.09 change to  `req.lcm.gen.02`

[RA2 Ch02] req.inf.ntw.09 change to req.lcm.gen.02

---

CONTRIBUTING.md

[TSC] Update CONTRIBUTING.md

---

doc/tech/release_notes/release_process.md

Modified the duplication of the figure number and reworded the figure and table name

Rewording & Minor bug fix

---

doc/ref_model/chapters/chapter05.md

[RM Ch05] Park compute intensive profile

---

doc/ref_arch/kubernetes/chapters/chapter08.md

[RA2 Ch08]: Adding NUMA aware hugepages gap

---

doc/ref_model/chapters/chapter04.md

Add 32vCPU/64GB transitional flavour

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

This PR updates the hardware profile information in chp3. 
Closes #1042

[RI] update chp 03 with hardware profile info

---

doc/ref_model/chapters/chapter05.md

[RM Ch05]: Hugepages -> Huge Pages

---

doc/ref_cert/lfn/chapters/chapter03.md

[RI Ch03]: HugePages -> Huge Pages

---

doc/ref_arch/kubernetes/chapters/chapter03.md

Fixes #978 together with #1147

[RA2 Ch3]: Adding hugepage considerations

---

doc/ref_impl/cntt-ri/chapters/chapter09.md

Bringing https://github.com/cntt-n/CNTT/pull/810 content by @markbeierl in here and closing original one. (since there was restructuring happening)
Fixes #406

[RI Ch09] Pharos Details in Development Chapter

---

doc/ref_model/chapters/chapter01.md
doc/ref_model/chapters/chapter08.md

[RM Ch01, Ch08]: Compliance to conformance

---

doc/ref_model/chapters/chapter04.md

[RM Ch03] Fix the typo

---

doc/ref_arch/openstack/chapters/chapter01.md

Deleted Scope and Roadmap
Added Document Organisation
Made other necessary edits
Fixes #260 
Fixes #1081

[RA-1 Ch01] Clean & Finalise Chapter 1 content

---

doc/ref_arch/openstack/chapters/chapter04.md

Issue Fixes #1088
Fixed defects that could be found.
**Did not address the following, could not find a bug:**
4.3.1:  “A high level overview … their sizing rules (to be developed).
>> Delete “ (to be developed)”
>> @scottsteinbrueck says could not find bug
4.7:  Architectural Drivers – Requirements Traceability
>> Delete from TOC and content
>> @scottsteinbrueck says could not find bug
**Did not address the following, consider a new issue to address:**
4.3.1:  Should we add “stateless/stateful” for the service components?
>> @scottsteinbrueck says @pgoyal01 to consider a new issue to address
4.3.10:  Cyborg
>> 4.3.1. VIM Core Services; where to place “Cyborg”
>> @scottsteinbrueck says @pgoyal01 to consider a new issue to address
4.4:  Do we need a section on SW and HW Host profiles?
>> …

[RA-1 Ch04] Minor Corrections

---

doc/ref_arch/openstack/chapters/chapter04.md

Updated tables to fix heading issue which listed "Control Server" instead of "Value" as second column. 
fixes #1220

RA-1 Ch04 Update chapter04.md to fix error with table headings

---

doc/ref_cert/lfn/chapters/chapter03.md

Fixes #1212 
Adds Requirements Traceability Matrix (RTM) for RM and RM-1 requirements with coverage mapping to Test Cases &/or Test Scenarios.

[RC1 - Ch03] Adds RTM to RC1 Ch3

---

doc/ref_arch/kubernetes/chapters/chapter03.md

duplication of /ref_model in the reference path.

[RA2 CH3] Invalid URL

---

doc/ref_impl/cntt-ri/chapters/chapter09.md

Fixes #1224 
- Updates TOC (and sub-headings so navigation matches TOC)
- Adds new 9.3 NFR Considerations Section
- Adds new 9.3.1 Traffic Generators & NIC sub-section

[RI-1 Ch09] General Baldy cleanup for RI doc

---

doc/ref_arch/kubernetes/chapters/chapter04.md

Use wording from CNCF TUG Cloud Native Principles document.
Fixes #990

RA2 Ch4 - update 4th bullet

---

doc/ref_arch/kubernetes/chapters/chapter02.md

RA2 Ch2 - remove req.lcm.adp.03

---

doc/ref_arch/kubernetes/chapters/chapter02.md

RA2 Ch2 - remove req.kcm.06

---

doc/ref_arch/kubernetes/chapters/chapter02.md

RA2 Ch2 - remove req.kcm.03

---

doc/ref_arch/openstack/chapters/chapter06.md

[RA-1 Ch06] Initial Content on RBAC

---

doc/ref_model/chapters/chapter05.md

[RM] update '3 types' of profiles to '2 types'

---

doc/tech/README.md

Redirecting the link to the recently merged roadmap page.

Pointing the link to new roadmap

---

doc/ref_model/chapters/chapter02.md

[RM Ch02]: Removing instance type from Ch02

---

doc/ref_arch/openstack/chapters/chapter01.md

Add section "CNTT OpenStack Reference Release"
Fixes #1229

[RA-1 Ch01] Add section on  OpenStack Release

---

doc/ref_model/chapters/chapter09.md

[RM] Fix reference to figure 9.2

---

doc/ref_model/chapters/chapter04.md

[RM] Add note on overbooking to allocation ratio

---

doc/ref_arch/kubernetes/chapters/chapter02.md

RA2 Ch2 - uncomment and change req.kcm.08

---

doc/ref_model/chapters/appendix-a.md

Fixes https://github.com/cntt-n/CNTT/issues/750

[RM] Exceptions

---

doc/ref_arch/kubernetes/chapters/chapter02.md

RA2 Ch2 - remove req.kcm.01

---

doc/ref_arch/kubernetes/chapters/chapter02.md

RA2 Ch2 - update value of e.nfvi.res.cap.005

---

doc/ref_model/chapters/chapter01.md

Diagram lagged the text which uses it, in approval. Updated placeholder to point to actual diagram.

[RM] Added Link to Network Layering Diagram

---

CONTRIBUTING.md

[TSC CONTRIBUTING]: Allow issue self assignement

---

doc/ref_model/README.md

[RM README]: Fixing glossary link

---

doc/ref_model/chapters/chapter04.md

Remove internal availability/reliability metrics, and renumber tables as 
needed.
Fixes #186.

[RM] Remove Internal availability/reliability metrics

---

doc/ref_arch/openstack/chapters/chapter04.md

Changed title of 4.2.3.3 to say "conformant" (Issue #988)

[RA-1 Ch04] compliant/conformant

---

doc/ref_arch/openstack/chapters/chapter03.md

1. replace "compliance" and "compliant" with "conformance" and "conformant" (Issue #988)
2. Edit some language to make it clearer and concise.

[RA-1 C03] Language edits

---

doc/ref_arch/openstack/chapters/chapter05.md

Edit 5.1 to change "compliance" to "conformance" (Issue #988). Some minor language edits.

[RA-1 Ch05] conformance/compliance

---

doc/ref_arch/README.md

Spelling mistakes

---

doc/ref_arch/kubernetes/chapters/chapter01.md

Moved cloud native principles link to the github link

[RA2 Ch02]: Cloud native principles link to the github link

---

doc/ref_arch/openstack/chapters/chapter06.md

Fixed #1302 
Updated outline and added section placeholders

[RA-1 Ch06] Initial Content on Audit Logging

---

doc/ref_arch/openstack/README.md
doc/ref_arch/openstack/chapters/chapter01.md

1. Change Compliant to Conformant (Issue #988)
2. Changed language of 1.1 and 1.3

[RA-1 Ch01] Language Fixes

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch03]: Adding compute resource isolation to Ch03

---

doc/ref_model/README.md
doc/ref_model/chapters/chapter03.md
doc/ref_model/chapters/chapter04.md
doc/ref_model/chapters/chapter05.md
doc/ref_model/chapters/chapter06.md
doc/ref_model/chapters/chapter07.md

Fixes https://github.com/cntt-n/CNTT/issues/1345
There is a need to include space after each table for it to be rendered correctly.

[RM] Fix tables

---

doc/ref_impl/cntt-ri/chapters/chapter08.md

Delete 7.5.1.2 Deployment: Installer & Install Steps
Change the level for 8.5.1.2 Deployment: Installer & Install Steps, and sub-sections within
Fixes #1342

[RI-1 Ch08] Delete Duplicate Content

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2 Ch02] Spelling mistakes

---

doc/tech/policies.md

This is more maintenance work. Cloning merged PR #1354 back to tech doc. This is getting old - docs need to be fixed to not require this continual maintenance work.
NOTE: **There is no new content in this PR.** This replicates agreed content from merged PR #1354

[Tech] Clone Merged PR from RM to Tech A.5

---

doc/ref_arch/openstack/README.md

[RA-1 README] Delete Terminology from TOC

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 Ch04] update of 4.2.2.3 and 4.2.2.5

---

doc/tech/glossary.md

[Tech Glossary] OpenStack related terms

---

doc/ref_arch/kubernetes/chapters/chapter04.md

[RA2 Ch04]: Runtime requirements

---

doc/tech/glossary.md

Terminology For Decoupling Applications From Infrastructure, Platform and Other Application Functionality. It was before in #789 that I will close.

[Tech] Terminology for Decoupling

---

doc/ref_arch/kubernetes/chapters/chapter04.md

[RA-2 Ch04] Spelling changes

---

doc/ref_arch/openstack/chapters/chapter03.md

remove "however, for small sites, a legacy topology (access/aggregation switches) can be set up."

[RA-1 Ch03]: 3.4.2.2. Network

---

doc/ref_arch/openstack/chapters/chapter05.md

It also fixes a few nits to unify the tabs.
Closes #1076

[RA1] Add Barbican API

---

doc/ref_arch/kubernetes/chapters/appendix-a.md

Closes #981 
Should be merged only after #1265 was merged

[RA2 appendix]: Following RM SR-IOV exception

---

doc/ref_arch/openstack/chapters/chapter04.md

Add 4.1 Introduction 
Fixes #1152
Delete "content to be developed" from 4.2
Fixes #1153

[RA-1 Ch04] Introduction

---

doc/ref_arch/kubernetes/chapters/chapter04.md

This addresses the OS modularity requirement discussed in Prague and in #950 .

[RA2 Ch04] Added statement to not restrict container base OS

---

doc/ref_model/chapters/chapter07.md

Add Security Requirements at the end of the Chapter Section 11.7.
Also corrected a couple of reference errors.
Fixes #1114

[RM Ch07] Add Security Requirements

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA1 Ch4] More precise DPDK usage

---

doc/ref_arch/openstack/chapters/chapter02.md

Changing NFVI to Cloud Infrastructure

[RA1 Ch02]: Changing NFVI to Cloud Infrastructure

---

doc/ref_arch/openstack/chapters/chapter07.md

Add New 7.1 Introduction, 7.2 NFVI + VIM Configuration Management and 7.3 NFVI + VIM Maintenance Content.
Inputs from @iangardner22 @karinesevilla and Kodilinye Atuchukwu
Replaces PR 1351 (too many conflicts)
Fixes #1350

[RA-1 Ch07] 7.1 and 7.2 Content

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2 Ch02]: Adding missing network requirements form the table of Ch 4.5

---

doc/ref_model/chapters/appendix-a.md

Text on Levels of Decoupling from previous #789 that I will close. Here with all comments applied and without mentioning "CNTT".

[RM Appendix] Levels of Decoupling

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Updating link and wording for VIM Capabilities in RA2

[RA-2 C02] Fixing reference to Cloud Infrastructure management Capabilities from RA-2 VIM Capabilities section

---

doc/ref_arch/openstack/chapters/chapter03.md

Changes made; in some places instead of replacing NFVI, the sentence itself was changed.
Fixes #1403

[RA-1 Ch03] Change NFVI to cloud infrastructure

---

doc/tech/usecases.md

[Edge] Draft the initial content for Edge #1415 
•	Terminologies 
•	Objective ( High level Objective ) 
•	Scope ( focus on Edge Scope , in/out scope , Next Slide ) 
•	CNTT Edge Principle & Strategy 
•	CNTT Edge roadmap 
•	Use cases ( that CNTT Edge will focus )  
•	SDO ( Engagement with other SDOs)

[Edge] Develop content under Edge use case section

---

doc/ref_model/chapters/chapter04.md

[RM Ch4]: Two more ocassions of NFVI changed to Cloud Infrastructure

---

doc/ref_cert/lfn/chapters/chapter01.md

Fixing Typos and Sequencing the figure

[RC1][Ch01]: Fixing Typos

---

doc/ref_arch/kubernetes/chapters/chapter06.md

[RA-2 Ch06] Spelling changes

---

doc/ref_cert/lfn/chapters/chapter03.md

[RC1][Ch03] Fixing typo

---

CODEOWNERS

Adding Owners for Edge and NFG

[TSC] Update CODEOWNERS for RI-1, Edge, NFG

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA-1] Update section 3.2.5

---

doc/ref_model/chapters/chapter10.md

[RM Ch10]: Replacing NFVI and VIM

---

doc/ref_arch/openstack/chapters/chapter06.md

Fixes #1217 
Initial Content for 6.3.3

[RA1 Ch06] Confidentiality & Integrity

---

doc/ref_model/chapters/chapter08.md

Cleaning out chapter 8 so people don't waste time "fixing" it, before we've started the new content.

[RM Ch08] Purge Content Moved to RC

---

doc/ref_model/chapters/chapter02.md

Change VNF to Workloads [VNFCs/Micro-service]
for digrams, I need your support @rabi-abdel @kedmison

[RM-Ch02 ] Change VNF to Workloads

---

doc/ref_model/chapters/chapter03.md

Changes to 3.3; align 3.3 with 3.1
Fixes #716

[RA-1 Ch03] Update Section 3.3

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

Reference to "C" and Compute intensive exists in both text and Tables -- need deletion
Closes #1348

[RI1 Ch03]Delete References to Compute Intensive

---

doc/ref_cert/lfn/chapters/chapter05.md

General clean up, and delete the session for 3rd party tools.

[RC1 chp05] General clean up

---

doc/ref_arch/openstack/chapters/chapter05.md

[RA1] Add minimal Heat template_version supported

---

doc/ref_cert/lfn/chapters/chapter03.md

It completes the changes in Functest:
- https://gerrit.opnfv.org/gerrit/c/functest/+/69993
- https://gerrit.opnfv.org/gerrit/c/functest/+/69926
Closes #1473

[RC1] Add tempest_heat

---

doc/ref_arch/openstack/chapters/chapter02.md

Incorporate RM 7.11 Consolidated Security Requirements in RA-1 CH02 2.3.8 (Requirements) and 2.4.8 (Recommendations).
To Do: Add Traceability
Fixes #1519

[RA-1 Ch02] Incorporate RM 7.11 Security

---

doc/tech/usecases.md

This is to review and agree on the structure and the content for use cases 1, 2, & 3.
Once agreed. I can put the content for use cases 4 & 5. (vRAN & Remote Surveillance with Video Analytics)
Note - Can I assign to "Team" instead of individual accounts?

[Edge WS] Edge_use_cases_1_2_3_Update usecases.md

---

doc/ref_arch/openstack/chapters/chapter06.md

Fixes #1545 
Bogometer: Still developing content
Wording 6.2

[RA1 Ch06] Minor: bogometer change + wording

---

doc/ref_arch/openstack/chapters/chapter06.md

[RA-1 Ch06] Initial Content on System Hardening

---

doc/ref_model/chapters/chapter04.md

This change proposes a forward compatibility framework.
Closes #1009

[RM Ch4]: Forward compatibility

---

doc/ref_model/chapters/appendix-a.md

[RM Appendix - A] Renaming the chapter

---

doc/ref_model/chapters/chapter05.md

[RM Ch05] Grammar correction.

---

doc/ref_cert/lfn/chapters/chapter01.md

check on typo, modify words not accurate for RC
Fixes #1164

[RC 1 chp 01] general clean up for chp01

---

doc/ref_cert/lfn/chapters/chapter02.md

mainly modify the first half of the chp02. General clean up for the overall document. Lots of details mentioned in the second half of this chp which may need further discussion.

[RC1] General clean up for chp02

---

doc/ref_arch/openstack/chapters/chapter06.md

Add "6.3.5 Image Security" Content

[RA-1 Ch06] 6.3.5 Image Security

---

doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 Ch3+Ch4] Provide content in 3.5 and Remove 4.5 to address OpenStack Topology

---

doc/ref_arch/openstack/chapters/chapter06.md

[RA1 Ch06] Security LCM

---

doc/ref_cert/lfn/chapters/chapter03.md

They are outdated and then falsy duplicate RM and RA tabs.

[RC1] Remove falsy duplicated req tabs

---

doc/tech/usecases.md

@Karimrabie @petorre @hdamker @sukhdevkapur 
Closes https://github.com/cntt-n/CNTT/issues/1415

[Edge WS ] Initial Content

---

doc/ref_arch/kubernetes/chapters/chapter04.md

This change implement the changes of Ch02 by #1524.
Closes #1523
Closes #1112
Closes #1499

[RA2 Ch4]: Implementing RA2 reorganisation to Ch4

---

doc/ref_arch/openstack/chapters/chapter06.md

Fixed #1554 
Also fixed table format, but left the img and heading ID along as MD didn't work properly for them.

[RA-1 Ch06] Replaced HTML lists with Markdown

---

doc/ref_model/chapters/chapter03.md
doc/ref_model/chapters/chapter05.md

Table 5-7: Virtual Networking Acceleration features ---->Table 5-7: Cloud Infrastructure Platform services.
Also, added following in the table as minimum requirements
Database as a service e.g Cassandra
Queue e.g Rabbit MQ
LB and HA Proxy

[RM Ch03] Fixes issue#1465

---

doc/tech/glossary.md

[Tech Glossary] Clarifying terminology of CPU and threads

---

doc/ref_cert/lfn/chapters/chapter01.md

add velidation test to address issue rased in #1315
close #1315

[RC1 Chp01] add velidation test

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1] Update Bogo Meter

---

doc/ref_model/chapters/chapter09.md

[RM Ch09]: Correction of data collection requirement

---

doc/ref_impl/cntt-ri/chapters/chapter06.md

[RI Ch06] Editorial changes in the Installer prerequisite

---

doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter03.md

Typos + clean up of comment or obsolete content + last table with an empty line

[RA1 Ch02 + Ch03] Typos + clean up

---

doc/tech/usecases.md

Hello,
Thanks to review the content for vRAN use case.
The fourth use case.

[Edge]Usecases_vRAN_add.md

---

doc/ref_arch/kubernetes/chapters/chapter05.md
doc/ref_arch/openstack/chapters/chapter03.md
doc/tech/glossary.md

@YuPengZTE - I have not changed all instances as some are quotes or correct in context.  Hope it makes sense.
Fixes #1534

[RA2 Tech] Change containeri[s|z]ed to cloud native where appropriate

---

doc/ref_impl/cntt-ri/chapters/chapter01.md

Correction of a broken link to the new location of terminology.

[RI1 Ch1] Minor link correction

---

doc/ref_arch/kubernetes/chapters/chapter01.md

[RA2 Ch01]: Correction of principles link

---

doc/ref_arch/kubernetes/chapters/chapter01.md

[RA2 Ch01]: Fix principle link - baldy

---

doc/ref_arch/kubernetes/chapters/chapter01.md

[RA2 Ch1] Link correction

---

doc/ref_impl/cntt-ri2/chapters/chapter01.md

[RI2 Ch1] - initial content

---

doc/tech/openstack-release.md

Fixes issue #1596 
Event added:
"major change on an OpenStack mandatory service's API"

[Tech OSTK-release] Triggering events: addition

---

doc/ref_model/chapters/chapter05.md

Replaced "content to be developed" by "Please see the [RM Security Chapter](./chapter07.md) and, in particular, the [Consolidated Requirements](./chapter07.md#711-consolidated-security-requirements) section."
Same fix was performed for Master branch (PR #1671) .
Fixes #1669

[RM Ch05] Fix 5.1.4 content for Baldy Release

---

doc/ref_model/chapters/chapter05.md

[RM Ch05] Fix format in 5.1.5 under Table 5.7

---

doc/ref_model/chapters/chapter05.md

Baldy release fix (master fixed in PR #1674)
Fixes #1673

[RM Ch05] Baldy: Fix format in 5.1.5 / Table 5.7

---

doc/ref_model/chapters/chapter07.md

#1676
part of RM CH07 re-arrange

[RM CH07 ] Security remove 7.2

---

doc/ref_impl/cntt-ri/chapters/chapter06.md

[RI01 CH06] Editorial changes in the Installer Prerequisite

---

doc/ref_cert/lfn/chapters/chapter02.md
doc/ref_cert/lfn/chapters/chapter03.md
doc/ref_cert/lfn/chapters/chapter08.md

Cherry picking fc0f671 of #1684 to Baldy.

[RC1 Ch2,Ch3,Ch8]: link corrections - baldy

---

doc/ref_impl/cntt-ri/chapters/chapter01.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

Cherry picking 72aa987  of  #1685 to Baldy.

[RI1 Ch01,Ch08]: Link corrections

---

doc/ref_model/chapters/chapter10.md

Moved gaps from RA-1 into seperate subsections of Section 10.3

[RM-CH10] Moved gaps from RA-1 

---

doc/ref_impl/cntt-ri2/chapters/chapter03.md

Initial content on lab requirements for chapter 03.
closes: #1528
Signed-off-by: Georg Kunz <georg.kunz@est.tech>

[RI2] Initial content for lab requirements

---

doc/ref_arch/kubernetes/chapters/chapter05.md

[RA2 Ch05]: Clarifications to security

---

doc/ref_model/chapters/chapter07.md

https://github.com/cntt-n/CNTT/issues/1676

[RM CH07] 7.1 Introduction re-writing

---

doc/ref_model/chapters/chapter05.md

[RM Ch05] Removing Hyperthreading

---

doc/ref_impl/cntt-ri2/chapters/chapter04.md

[RI2 Ch04] Initial Draft

---

artefacts/README.md

This pr adds the instructions on how to handle svg images.
closes: #1461

[TSC]: Handling of svg images

---

README.md

It would ease the different type of users to go the best target.
The list will be updated according to the next updates (e.g. RC2).

[ROOT] Add navigation tips on top document

---

doc/tech/glossary.md

[Tech Glossary]: Clarifications to cloud infrastructure

---

doc/ref_model/chapters/chapter07.md

Interchange 7.4 ( scope ) with 7.3

[RM CH07 ] Interchange 7.4 with 7.3

---

doc/ref_model/chapters/chapter03.md

[RM CH03] Typo "delete |"

---

doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter03.md

[RA1 Ch02, Ch03] Multithreading corrections

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

re-introducing https://github.com/cntt-n/CNTT/pull/1628

"[RA1]RC1] Skip manage_snapshot in CNTT""

---

doc/ref_model/chapters/chapter06.md

Move Table 6.3 from md to html to allow rowspans
Also changed the bogo meter to "dickering over fine points"
Fixes #1709

[RM Ch06]  Fix Table 6.3

---

doc/ref_model/chapters/chapter07.md

Issue #1676 
Changes to Section 7.9, 7.5.4, 7.6.8 and 7.7.1.

[RM Ch07] Change 7.9

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2Ch02] Removing hyperthreading

---

doc/ref_impl/cntt-ri/chapters/chapter05.md

[RI1 Ch05]: Removing Hyperthreading

---

doc/ref_arch/openstack/chapters/chapter02.md

[RA-1 Ch02] Rename column in 2.4 Recommendations

---

doc/ref_model/chapters/chapter08.md

Renamed Chapter 8 title and removed the empty skeleton and bogometer

[RM Ch08] Chapter 8 renamed as blank

---

doc/ref_model/README.md

Changed title of Chapter 8 in the RM Table of contents

[RM - ToC] Changed title of Ch8 in ToC

---

doc/tech/usecases.md

[Edge ] SDO interlocking

---

doc/ref_model/chapters/chapter01.md

Restructured Chapter 1 as per the GSMA requirements

[RM Ch01] Restructure to fit GSMA format

---

doc/ref_model/chapters/chapter04.md
doc/ref_model/chapters/chapter05.md

Fixes #816
Once WIP label is removed will be available for review but please suggest corrections as you see errors.

[RM Ch04-05] Consistency and Typo Corrections

---

doc/ref_arch/openstack/chapters/chapter02.md

Move "should" and "may" requirements from 2.3 to 2.4
This is for Baldy Release
Fixes #1618

[RA-1 Ch02] Clean 2.3 -- "should" and "may" reqmts

---

doc/ref_model/chapters/chapter02.md

The GSMA feedback addressed and some minor typos fixed.
Global table and figure numbering will be fixed separately.

[RM Ch02] GSMA fedback addressed

---

doc/ref_arch/openstack/chapters/chapter08.md

[RA-1 Ch08] Delete 4 gaps moved to RM Ch 10.3

---

doc/ref_model/chapters/chapter04.md

Added an updated Underlay and Overlay Networking concepts from the Baldy release approved Tech/approach.md

[RM Ch04] Underlay and Overlay Networking concepts

---

doc/ref_model/chapters/chapter04.md

Added an updated version of Hardware and Virtual Infrastructure Layer concepts from the Baldy approved Tech/approach.md

[RM Ch04] Hardware and Virtual Infrastructure Layer concepts

---

doc/ref_model/chapters/chapter04.md

Added an updated version of the Software Defined Underlay and Overlay Networking concepts from the Baldu approved Tech/approach.md

[RM Ch04] Software Defined Underlay and Overlay Networking concepts

---

doc/ref_model/chapters/chapter04.md

Added updated content for Programmable Networking Fabric concept from approved Baldy release Tech/approach.md

[RM Ch04] Programmable Networking Fabric concept

---

doc/ref_arch/kubernetes/chapters/chapter05.md

[RA2 Ch6]: Clarifications to container image handling

---

doc/ref_model/chapters/chapter04.md
doc/tech/usecases.md

https://github.com/cntt-n/CNTT/issues/1748#event-3506937302
Fix 4.2.5 Profile Capability Mapping
SmartNIC
FPGA
GPU
Allocation ratio

[RM CH04] Fix 4.2.5 Profile Capability Mapping

---

doc/ref_arch/kubernetes/chapters/chapter04.md

[RA2 Ch4] Change to specifications

---

doc/common/chapter00.md

recommended to move from #1738 to here by @pgoyal01

[RM TSC] Add requirements principles

---

CODEOWNERS
README.md
doc/ref_cert/RC2/figures/bogo_ifo.png
doc/ref_impl/cntt-ri/chapters/chapter08.md

[ALL] Fix former links (lfn -> RC1)

---

doc/ref_arch/openstack/chapters/chapter01.md
doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter04.md

[RA1 All Ch] Update to Train Issues #1815

---

doc/ref_model/chapters/chapter02.md

update ch02 with Edge use cases

[RM CH02] update ch02 with Edge use cases

---

doc/ref_model/chapters/chapter07.md

fixes #1504 
Recommendation to use SELinux to control access to resources.
Additions into 7.5.1.2 and 7.11.2 req.sec.sys.014

[RM Ch07] Enforce mandatory access control: reco

---

README.md
doc/ref_cert/README.md

[TSC] Fixes few dead links 

---

doc/ref_model/chapters/chapter04.md

Fixes #1582 
Instead of deleting section as would require renumbering making it as TBD
Change should also be made in Baldy.

[RM Ch04] Change Title of 4.2.6

---

doc/ref_impl/cntt-ri2/chapters/chapter04.md

Issue #1734 
Adds details to Chapter 4.3.2 about provisioning Kubernetes using BMRA

[RI2 Ch4.3.2] Kubernetes Provisioning

---

doc/ref_model/chapters/chapter07.md

Fixes #1503 
Per @tianliangma's comment: 
Memory and CPU running core added in description (7.3.3) + link to the requirement

[RM Ch07] Isolation between tenants

---

doc/ref_arch/openstack/chapters/chapter08.md

[RA1 Ch08] Move Multi-cloud gap from RA1 Chapter 8 to RM

---

doc/ref_model/chapters/chapter09.md

Addressing Issue #1251 
Removed unnecessary diagram and a part of the contents being a quite incorrect and unnecessary commentary.

[RM Ch09.1] Introduction

---

doc/ref_arch/openstack/chapters/chapter06.md

issue #1716 (fixes partially)
To comply req sec.gen.002
Merge of sections 6.3.2.1 Function and 6.3.2.2 Software into section 6.3.2.2 Function and software
Rename section 6.3.2.1 Function into Password policy 
Content added about password policy

[RA1 Ch06] System Hardening, password policy

---

doc/ref_model/chapters/chapter03.md

Fixes #1851 
Section 3.2.3 Storage
The original storage resource description addresses only about Block device storage.
The intent of this proposal is to make it more generic and to reflect storage diversity

[RM Ch03] Storage resource description

---

doc/ref_model/chapters/chapter07.md

Updated: sec.gen.001, sec.gen.002, sec.gen.004, sec.gen.010
Added: sec.gen.015
@pgoyal01  and @tomkivlin  please make changes to your RA document.
@pgoyal01 the reference model team (ref-m) was not available in the Reviewers drop down.
Fixes #1884

[RM CH07] Update section 7.11.1. System Hardening

---

doc/ref_arch/openstack/chapters/chapter02.md

Recommended changes to section 2.3.8.2. Platform and Access

[RA1 Ch02] Update chapter02.md

---

doc/ref_arch/kubernetes/chapters/chapter06.md

All gaps are reformulated to use the template.
6.2.4 reformulated to contain the ingress, egress and load balancers.
closes: #1340 
closes: #1341

[RA2 Ch6]: Reformulate gaps and adding ingress and egress

---

doc/ref_arch/kubernetes/chapters/chapter06.md

[RA2 ch6] - erroneous requirement reference

---

doc/common/chapter00.md

This PR is meant to provide clarity and technology independence for the principles around dependencies between virtual and physical infrastructure, and network workloads in alignment with the evolved Reference Model and advances in technology. It moves technology dependent policies, exceptions and requirements into the technology dependent Reference Architectures specifications and the downstream implementation specs. It also changes the verbiage form the commandments to the principles.

[Chapter 00] Principles update - Acceleration alignment

---

doc/ref_arch/kubernetes/chapters/chapter03.md

Resolves #1850 
Also wrapped lines to 80 chars for future ease of reviews.

[RA2 Ch03] - Tweak wording to cover both physical and virtual

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Resolves #1795 
Resolves #1829

[RA2 Ch2] Correct requirements pull through from RM

---

doc/ref_arch/openstack/chapters/chapter02.md

* [RA1 Ch02] APIs: requirement added per service
fixes #1621
Section 2.3.4 APIs
Requirements added for each OpenStack Mandatory Service
* Update doc/ref_arch/openstack/chapters/chapter02.md
Co-authored-by: Pankaj Goyal <52107136+pgoyal01@users.noreply.github.com>
* 2.3.4 Update per Pankaj's comment
"CNTT conformance" removed
* Typo
Co-authored-by: Pankaj Goyal <52107136+pgoyal01@users.noreply.github.com>
(cherry picked from commit 3c632cd8ffce7120ca624dbe26fcc30e7cf35f09)

[RA1 Ch02] APIs: requirement added per service (#1621)

---

doc/ref_arch/openstack/chapters/chapter02.md

Hardening Requirements alignment:: Section 2.3.8.1 and 2.4.8.1 align with [RM 7.9.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#79-consolidated-security-requirements) (RM PR #1892 )

[RA1 Ch02] Section 2.3.8./2.4.8 align with RM 7.9.1

---

doc/ref_model/chapters/chapter03.md

In [RM Chapter 3](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md) 3.3.1 is Virtual Infrastructure Manager. Hardware Infrastructure Manager should be 3.3.2. TOC and links are correct, text is not.
Fixes #1939 .

[RM Ch3] Fix numbering sequence for 3.3.2 HW Infra. Mgr.

---

doc/ref_arch/openstack/chapters/chapter06.md

Update chapter to address Monitoring and Audit requirements.
Fixes #1718

[RA1 Ch06] Update chapter for Monitoring and Audit

---

doc/ref_arch/openstack/chapters/chapter02.md

[RA1] Nit: access to -> access

---

doc/ref_arch/openstack/chapters/chapter02.md

Co-authored-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 37a074cee1d2e229ef9557d9d6c946781193a888)

[RA1] Nit: access to -> access (#1945)

---

doc/ref_model/chapters/chapter10.md

Editorial change fixing level of titles of subsection of 3.5

[RM Ch 3.5] Fixed level of subsections

---

doc/ref_model/chapters/chapter02.md

https://github.com/cntt-n/CNTT/issues/1966

[RM CH02 ] Use cases renumbering 

---

doc/ref_model/README.md
doc/ref_model/chapters/chapter01.md

Fixes #1961 
Alignment with chapters7 and 8 scope

[RM Ch01] Update for chapters 7 and 8

---

doc/ref_model/chapters/chapter04.md

Chapter 4.3 Networking Figure numbering alignment and Table of Content insertion
Fixes Issue #1967

[RM Ch4] Ch 4.3 Figure number alignment and ToC insertion

---

doc/ref_model/chapters/chapter03.md

(As per discussions on RM calls) This is new section 3.6 Storage similar like there is 3.5 Network .
Fixes #1943 .

[RM Ch3] Add Section 3.6 Storage

---

doc/ref_model/chapters/chapter07.md

Fixes #1959 
7-1 Introduction's text adapted to content
7.3.2 Note added about "platform" word
7.3.2 Requirement ref removed
7.5.4 Text modified
7.5.8 -> 7.5.7 numbering error, title and text  modifed
7.6 typo
7.6.3 VM oriented section, text modified
7.7 Typo, redundancy  removed
7.8 review and modifications of reference

[RM Ch07] Clean up sections 7-1 to 7-8

---

doc/ref_arch/openstack/chapters/chapter01.md

Add FPGA/Accelerator Exceptions to 1.4.1.1 Technology Exceptions
Fixes #1950

[RA1 Ch01] Add FPGA/Accelerator Exceptions

---

doc/ref_arch/openstack/chapters/chapter06.md

Add language suggested by @iangardner22 
Fixes #1936

[RA1 Ch06] 6.3.7.2 What to Log

---

doc/ref_arch/openstack/chapters/chapter08.md

Created on behalf of @iangardner22 
Fixes #1052

[RA1 Ch08] Gaps - Autoscaling

---

doc/ref_arch/openstack/chapters/chapter08.md

Replace Pike with Train
Do we really need this Section?

[RA1 Ch08] 8.2 OpenStack Release Gaps

---

doc/ref_model/chapters/chapter02.md

Fixed ToC links and other items related to added section on use Cases

[RM Ch2] Renumbering and ToC fixes 

---

doc/ref_arch/openstack/chapters/chapter03.md

Fix broken reference in section 3.2.5.1 of RA1

---

doc/ref_model/chapters/chapter07.md

Fixes #1981 
7.4.1.2 Requirements sorted by category
7.4.2 Duplicated requirements, covered in 7.4.1.2, deleted

[RM Ch07] Restructuring 7.4.1.2 and 7.4.2

---

doc/ref_cert/README.md

[RC02] Fix Test Integration Introduction

---

doc/ref_arch/openstack/chapters/chapter08.md

Placement service added to the list + some typos

[RA1 Ch08] OpenStack release gaps

---

doc/ref_impl/cntt-ri2/chapters/chapter02.md

To fill out in subsequent PR(s) - let's use this PR to agree the structure.
Closes #1527

[RI2 Ch2] - initial structure

---

doc/ref_arch/kubernetes/chapters/chapter04.md

Based on the comments on #1932 pull request by Tom, creating new merge request.
Fixes #1636

[RA2 Ch04] - Container runtime configs. (Issue 1636)

---

doc/ref_arch/openstack/chapters/chapter06.md

Fixes #1717 
Content added to reflect chapter 2 requirements 
Wrong link modified

[RA1 Ch06] Image security

---

doc/ref_arch/openstack/chapters/chapter02.md

2.2.6 Cloud Infrastructure Security requirements 
Traceability: references added

[RA1 Ch02] Security requirements traceability

---

doc/ref_arch/openstack/chapters/chapter06.md

[RA1 Ch06] Updated content for RBAC

---

doc/ref_model/README.md

Out-of-date status changed to: Release ready

[RM Status] Update status

---

doc/common/references.md

Added reference to ETSI GR NFV 002 V1.2.1, removed bogometer

[RM References] update

---

doc/common/chapter00.md

Updated references to ETSI and GSMA documents
Added a comment about CNCF - CNTT collaboration around Rx-2

[RM  chapter00] Reference updates

---

doc/ref_model/chapters/chapter01.md

Updated references to ETSI document

[RM Ch01] Updated references in RM Intro

---

doc/ref_model/chapters/chapter07.md

@zwarico made changes to Security requirements in RA1 and these also need to be made in RM (@walterkozlowski) and RA2 (@tomkivlin)

[RM Ch07] Update CH07 with RA1 changes by @zwarico

---

doc/ref_model/chapters/chapter10.md

Updated Intro to Chapter 10 as the wording was out of date

[RM Ch10] Update Intro

---

doc/ref_arch/kubernetes/chapters/appendix-a.md
doc/ref_arch/kubernetes/chapters/chapter01.md

[RA2] remove ref to rm appendix and move exceptions to chapter01.md

---

doc/ref_model/README.md

Removing Appendix A "Guidance For application Vendors" from ToC of RM.  These guidelines will be discussed in RAs as they are technology specific.

[RM Toc] Update

---

doc/ref_model/chapters/chapter01.md

Removed the only remaining reference to Appendix A

[RM Intro] Removed reference to Appendix A

---

doc/common/glossary.md

[Glossary] Fixing the definition of Workload

---

doc/ref_arch/kubernetes/README.md
doc/ref_arch/kubernetes/chapters/chapter01.md
doc/ref_arch/kubernetes/chapters/chapter02.md
doc/ref_arch/kubernetes/chapters/chapter05.md
doc/ref_arch/kubernetes/chapters/chapter06.md

[RA2] bogo meter check

---

doc/ref_impl/cntt-ri2/README.md
doc/ref_impl/cntt-ri2/chapters/chapter01.md
doc/ref_impl/cntt-ri2/chapters/chapter03.md
doc/ref_impl/cntt-ri2/chapters/chapter04.md

[RI2] bogo meter check

---

doc/common/glossary.md

[Glossary] Creating the definition of a tenant instance

---

doc/ref_model/chapters/chapter07.md

Typos 
Missing punctuation
References in section 7.9.8

[RM Ch07] Proofreading

---

doc/ref_arch/openstack/chapters/chapter04.md

Figure 4-6 and 4-7 Caption Alignment: Added a >br> between the Figure and Caption

[RA1 Ch04] Figure Caption Alignment

---

doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter06.md
doc/ref_arch/openstack/chapters/chapter07.md

Typos, links
Chapter02: Alignement with RM Chapter 7 wording and last modifications

[RA1 Ch02, Ch06, Ch07] Proofreading

---

doc/common/glossary.md

1. Moved Prometheus to be alphabetical in sequence
1. Added bullets to some terms

[RM Glossary] Proofreading

---

doc/ref_model/chapters/chapter07.md

Bug in table 7.2: requirement without reference  -> requirement merged with req.sec. sys.001, alignment with last modification made in RA1

[RM Ch07] 7.9.2 Proofreading

---

doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md

[RA1 Ch2, Ch4] T-shirt removal

---

doc/ref_model/chapters/chapter01.md

Added introductory remarks about the problem statement to RM Chapter 1 Introduction.

[RM Ch1] Problem statement

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA1 CH4] Correcting capitalization of NUMA and vCPU

---

doc/ref_arch/openstack/chapters/chapter02.md

[RA1 Ch02] CPU SKU -> CPU type

---

doc/ref_model/chapters/chapter05.md

[RM Ch5] Removing process

---

doc/ref_model/chapters/chapter04.md

[RM CH4] Removing aka

---

doc/ref_model/chapters/chapter03.md

[RM CH3] Capitalization of CPU

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA1 CH4] Adding SMT thread to the description of CPU pinning

---

doc/ref_model/chapters/chapter07.md

Per Pankaj's comments from PR#2081:
platform->Platform
must in bold
req.sec.sys.017 -> with X.509 standards issued by 
req.sec.lcm.012 -> access privilege

[RM Ch07] Typos + minor modifications

---

doc/ref_arch/openstack/chapters/chapter02.md

Per Pankaj's comments from PR#2081:
platform->Platform
must in bold
sec.sys.017 -> with X.509 standards issued by
sec.lcm.012 -> access privilege

[RA1 Ch02] Typos + minor modifications

---

doc/ref_model/chapters/chapter04.md

[RM Ch4]: Multiple vCPU corrections

---

doc/common/glossary.md

[Glossary]: adding the definition of CPU Type

---

doc/ref_arch/openstack/chapters/chapter02.md

Change [2.3.6 Operations and LCM Requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter02.md#236-operations-and-lcm): Fixes #2033

[RA1 Ch2] Change 2.3.6 Operations and LCM

---

doc/ref_model/chapters/chapter09.md

Changed from VNF to workload, added comments about ITIL and added a Note below the table 1.

[RM Ch9.1] Update to LCM Introduction

---

doc/common/abbreviations.md
doc/ref_model/chapters/chapter02.md

Fixes #2066 
Added CHF/CCS to list of 5G Core NFs (Control Plane).

[RM Ch2] Update list of network functions 

---

doc/ref_model/chapters/chapter09.md

Add Section 9.5 Automation: TOC and Structure

[RM Ch08] Add Section 9.5 TOC and Structure

---

doc/ref_arch/openstack/chapters/chapter04.md

Fixes #2046 
Replace "Content to be added" with an intro to the list of network items.

[RA1 Ch04] 4.2.3 Network Content

---

doc/ref_model/chapters/chapter03.md

Fixes #2051 
As per #2051 , RM calls and October vF2F RM session. @TFredberg , @qabpea , @walterkozlowski and I are preparing more PRs with text.

[RM Ch3] Section titles for HW Acceleration

---

doc/ref_arch/kubernetes/chapters/chapter05.md

Remove "must" as this chapter doesn't form part of the specification, it is guidance only.
Note this is grammar/typos only - not asking for a review of wording (please open new issues for that).
Resolves #1581

[ra2] ch5 re-word

---

doc/ref_model/chapters/chapter09.md

Fixes #2156 
Addition to section 9.5.2.1 to cover the software onboarding for cloud infrastructure services

[RM Ch09] SW onboarding for infrastructure

---

doc/ref_impl/cntt-ri2/chapters/chapter04.md

Added few lines about RI2 validation. As mentioned in the issue #2125, the feedback loop between RI2 and RC2 is still TBD. More details on that will be added later.

[RI2 Ch04] Add information about validation

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] Device Plugin Framework

---

doc/ref_arch/kubernetes/chapters/chapter04.md

closes #2040
closes #1916 
Column to be filled out in a separate PR/PRs.

[RA2] ch4 updated with RI2 traceability column

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] NFD

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] Hardware Acceleration

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] Scheduling pods with non-resilient apps

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] Memory management

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] CPU Management

---

doc/ref_impl/cntt-ri2/chapters/chapter03.md

Closes #2125  
Changes wording from RI2 feeding into RC2, to RC2 verifying RI2

[RI2 Ch3] Update purpose of RI2 wrt. RC2

---

doc/ref_model/chapters/chapter09.md

Add content for Pre-Tenant Creation:
1. Tenant Approval -- use, capacity, data centers, ..
1. Tenant Admin, Tenant Member and other Tenant Role approvals for user by role
1. Tenant Images and manifests approvals
1. ....

[RM Ch09] 9.5.3.1 Pre-Tenant Creation

---

doc/ref_model/chapters/chapter03.md

[RM Ch3] Types of Accelerators

---

doc/ref_model/chapters/chapter03.md

[RM Ch3] HW Acceleration Resources

---

doc/ref_model/chapters/chapter03.md

Caption for table already merged, as per discussion on RM call. Number will be 3-6 as 3-5 will come before with #2158 .
Towards fixing #2051 .

[RM Ch3] Table 3-6 caption

---

doc/ref_cert/README.md

[RC README]: Changing ex: to e.g.

---

doc/ref_impl/cntt-ri2/chapters/chapter04.md

[RI2 Ch04] Fix Broken Links in Section 4.4

---

doc/ref_model/chapters/chapter03.md

[RM Ch3] Firmware-programmable adapters

---

doc/ref_model/chapters/chapter03.md

Adding content to continue solving Issue #2050

[RM Ch03] HW Management content additions

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

[RI1 Ch3] Multiple vCPU corrections

---

doc/ref_arch/openstack/README.md
doc/ref_arch/openstack/chapters/chapter01.md
doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter04.md
doc/ref_arch/openstack/chapters/chapter06.md
doc/ref_arch/openstack/chapters/chapter08.md

readme: bogo meters update
Ch01: 1.5 "Elbrus release version"
Ch02: errors on links to RM + missing "" + typos
Ch04: typos
Ch06: typos 6.3.7.3 +bogo meter changed
Ch08: bogo meter update

[RA1] Proofreading

---

doc/ref_model/chapters/chapter05.md

[RM CH5] Minor editorial changes

---

doc/ref_model/chapters/chapter04.md

The attribute to be consider is the bandwidth necessary for each one of the configurations
Closes: #2194

[RM Chapter04] Replace Management Interface by Bandwidth on Table 4-13

---

doc/ref_model/README.md

Fix release date for CNTT RM Elbrus

---

doc/ref_cert/RC1/chapters/chapter02.md

[RC1 Ch2] Clarifying compute metrics measurement

---

doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

https://github.com/ansible-collections/community.general/blob/stable-2/CHANGELOG.rst

Update Ansible community general to 2.0

---

doc/ref_arch/kubernetes/README.md

Update latest release to CNTT Elbrus

---

doc/ref_cert/RC2/README.md

It continuously conforms with CNTT RA2.

Increment Bundle in RC2

---

doc/ref_model/README.md
doc/ref_model/chapters/chapter01.md
doc/ref_model/chapters/chapter02.md
doc/ref_model/chapters/chapter04.md
doc/ref_model/chapters/chapter05.md
doc/ref_model/chapters/chapter06.md

[RM] Removing outdated comments

---

doc/common/README.md

[TSC]: Removal of the broken link to approach.md

---

doc/_static/css/custom.css
doc/_templates/layout.html
doc/conf.py

[TSC RTD]: Remove width limitation of content

---

doc/index.rst
doc/ref_arch/README.md
doc/ref_cert/README.md

[RTD]: Fixing left side menu

---

CODEOWNERS

Remove myself as code owner for RA2 pages

[RA2] Update CODEOWNERS

---

doc/ref_arch/kubernetes/chapters/chapter02.md

fixes https://github.com/cntt-n/CNTT/issues/2203

[RA2 Ch2] remove req.gen.cnt.01

---

doc/ref_arch/kubernetes/chapters/chapter06.md

[RA2 Ch6]: Namespace user ID-s gap in Kubernetes

---

doc/ref_model/chapters/chapter10.md

Removing Gap 10.3.5 "Multi-cloud Architecture" as this topic is now covered in RM Chapter 8 "Hybrid Multi-Cloud: Data Center to Edge"

[RM Ch10] Removing Gap 10.3.5 Multi-cloud Architecture

---

doc/ref_model/chapters/chapter10.md

Adjusting subsections numbers and Chapter 10 ToC after removing 2 gaps

[RM Ch10.3] Adjusting ToC and numbers of Gaps section 10.3

---

doc/ref_model/chapters/chapter03.md

Updated layers description to align terminology to the diagram

[RM Ch03.01] Update layers definition to align with diagrams

---

CODEOWNERS

Removed myself as RI2 codeowner and added Rihab and James as Kuberef and Airship leads within RI2.

[TSC] Update CODEOWNERS

---

doc/ref_model/chapters/chapter03.md

Restructured Sec 3.2 as per Issue#  #2135

[RM Ch03.2] Restructuring Sec 3.2

---

doc/ref_model/chapters/chapter03.md

Fixes #2276  Update Service function chaining section in 3.5.1 : 3.5.1.1 Introduction

[RM Ch3] Update SFC Section 3.5.1

---

doc/ref_model/chapters/chapter03.md

Moved "Virtual Infrastructure Manager" section into "Virtual Infrastructure Layer" as 3.2.2; this is the next installment of addressing Issue [RM Ch03] Illogical sub chapter order #2135.  In the next PR, I will create "Hardware Infrastructure Layer" as a new section 3.3

[RM Ch03.2.2] Virtual Infrastructure Layer section

---

doc/ref_model/chapters/chapter03.md

Changing stricture for Hardware Infrastructure Layer 3.3. Section 3.4 left for future use

[RM Ch03] New structure for Hardware

---

doc/ref_arch/kubernetes/README.md

fixing the index after PR #2332

add chapters 6,7 to ra2 index

---

doc/ref_arch/kubernetes/chapters/chapter01.md
doc/ref_arch/kubernetes/chapters/chapter03.md

 [RA2] Changing CNTT to Anuket

---

doc/ref_model/chapters/chapter03.md

See Issues https://github.com/cntt-n/CNTT/issues/2374 https://github.com/cntt-n/CNTT/issues/2375 and https://github.com/cntt-n/CNTT/issues/2376

[RM Ch03] Storage Telemetry Definitions

---

doc/ref_model/chapters/chapter03.md

As there is no contents there it refers to Sec 3.5 Network

[RM Ch3] Virtual Network

---

doc/ref_model/chapters/chapter09.md

Removed for now as there is no contents or work on this topic. As per RM decision on 28 April 2021.

[RM Ch09] Tenant Networking Automation

---

doc/ref_impl/cntt-ri/chapters/chapter08.md

[RI1 CH8] Capitalize Kubernetes and Kubernetes Cluster

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

RM1 -> RM
Syntax issue to remove Compute Intensive

[RI1 Ch03] Proofreading Typos

---

doc/ref_model/chapters/chapter04.md

Closes #2398 
Update Section 4.1 with missing capabilities

[RM Ch04] Update Section 4.1 capabilities

---

doc/ref_model/chapters/chapter03.md

In Ch3 are three "Table 3-6".
Closes #2430

[RM Ch3] Fix table numbering

---

doc/ref_model/chapters/chapter02.md

[RM Ch04] 2.4.2 Table Format Error

---

doc/ref_arch/kubernetes/chapters/chapter03.md

From @arkadykanevsky and me towards closing #2255.

[RA2 Ch3] Containers Bare Metal and in VMs

---

doc/ref_arch/kubernetes/chapters/chapter03.md

From @arkadykanevsky and me.
This might better fit in some other chapter - guidance is welcome.
Closes #2421 .

[RA2 Ch3] Add Custom Resources

---

doc/common/policies.md

[Common Policies] Fix as per Issue #2418

---

doc/ref_arch/kubernetes/chapters/chapter04.md

[RA2 Ch4]: Adding NetworkPolicy requirement.

---

doc/common/abbreviations.md

Fixes Partially #2389 
Add Common Abbreviations
Correct some existing Typo's

[Common Abbreviations] Add Common Abbreviations

---

doc/ref_model/chapters/chapter07.md

Fixes #2313 
Addition of section 7.6.6 Zero Trust Architecture
Addition of requirement req.sec.sys.020 in 7.9.2

[RM Ch07] Zero Trust Architecture

---

doc/common/references.md

Partially Fixes Issue #2389 
Added external references -- please suggest any missing. Thanks

[Common References] Add references

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3] TOC missing "3.2.5.1 Operator Pattern"

---

doc/ref_arch/kubernetes/chapters/chapter06.md

This change adds a short human readeable description of the labels listed in Ch6.

[RA2 Ch6]: Adding human readeable description of the labels

---

doc/ref_cert/RC1/chapters/chapter01.md
doc/ref_cert/RC1/chapters/chapter03.md

[RC1] relative links

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA1 Ch03] Align with RM 2.4

---

doc/ref_arch/openstack/README.md
doc/ref_arch/openstack/chapters/chapter01.md
doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md
doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_arch/openstack/chapters/chapter06.md
doc/ref_arch/openstack/chapters/chapter08.md

[RA1 -all Ch] Proofreading

---

doc/ref_cert/RC1/chapters/chapter02.md

Co-Authored-By Rihab Banday <rihab.banbay@ericsson.com>

|RC1] nit: throughout -> throughput

---

doc/ref_cert/RC2/README.md

[RC2] Add Kali in Bundle/Version History

---

doc/ref_cert/RC1/README.md

[RC1] Add Kali in Bundle/Version History

---

doc/ref_cert/RC2/chapters/chapter02.md

It also adds the related test case description.

[RC2] Add netperf in RC2 test case list

---

doc/ref_model/chapters/chapter08.md

[RM] nit: end <sup>

---

doc/ref_model/chapters/chapter09.md

Else it's falsy considered as part of the tab

[RM] nit: Add black line before Table 9-1 ref

---

doc/ref_model/README.md

It formats the bundle history tab.

nit: format ref_model/README.md

---

doc/ref_arch/kubernetes/chapters/chapter03.md

[RA2 Ch3]: Clarifications to VM based worker nodes

---

doc/ref_arch/kubernetes/chapters/chapter07.md

[RA2 Ch7]: Correction of Related Requirements table in 7.2.9

---

doc/ref_cert/RC2/chapters/chapter04.md

[RC2 chapter04] Absolute link changed to relative link

---

doc/ref_cert/RC1/chapters/chapter03.md

nit: Format TC Mapping to Requirements tab

---

doc/ref_arch/kubernetes/chapters/chapter04.md
doc/ref_impl/cntt-ri/chapters/chapter06.md

Updated RI1(openstack) documents chapter 6--installer requirement according to the latest PDF2.0,  to specify all the necessary parameters in descriptor file.

RI1 documents update for PDF 2.0 definition

---

doc/ref_impl/cntt-ri/chapters/chapter02.md

[RI1 ch02] Absolute link changed to relative link

---

README.md

[TSC]: Update README in the root of the repo

---

doc/ref_cert/RC2/chapters/chapter02.md

https://github.com/kubernetes-sigs/kind/issues/2356

[RC2] Blacklist git_repo testing as discussed upstream

---

doc/common/references.md

Updates References with Security references required for Multi-Cloud Security (Issue#2314)

[RM Ch 7 &8] Update references.md with 

---

doc/ref_cert/RC1/chapters/chapter01.md
doc/ref_cert/RC2/chapters/chapter01.md

https://github.com/cntt-n/CNTT/issues/2603

[RC1][RC2] Remove falsy <br> in RC chapters

---

doc/ref_cert/RC1/chapters/chapter01.md
doc/ref_cert/RC1/chapters/chapter02.md
doc/ref_cert/RC1/chapters/chapter03.md
doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC1/chapters/chapter05.md
doc/ref_cert/RC1/chapters/chapter06.md
doc/ref_cert/RC1/chapters/chapter07.md
doc/ref_cert/RC1/chapters/chapter08.md
doc/ref_cert/RC2/chapters/chapter01.md
doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_cert/RC2/chapters/chapter04.md
doc/ref_cert/RC2/chapters/chapter05.md
doc/ref_cert/RC2/chapters/chapter06.md
doc/ref_cert/README.md

https://github.com/cntt-n/CNTT/issues/2603

[RC1][RC2] Remove all "Back" refs

---

doc/ref_arch/openstack/chapters/chapter04.md

A blank line creates a paragraph in markdown.

[RA1] Remove useless html paragraphs

---

doc/ref_arch/openstack/chapters/chapter01.md

[RA1 Ch01] Correct Typo/language and misc issues

---

doc/ref_arch/openstack/chapters/chapter08.md

[RA-1 Ch08] Typo's, spelling, language corrections

---

doc/ref_arch/openstack/chapters/chapter03.md

[RA-1 Ch03] Typo's, spelling, language corrections

---

doc/ref_arch/openstack/chapters/chapter06.md

[RA-1 Ch06] Typo's, spelling, language corrections

---

doc/ref_arch/openstack/chapters/chapter05.md

[RA-1 Ch05] Typo's, spelling, language corrections

---

doc/ref_arch/openstack/chapters/chapter02.md

[RA1 Ch02] Wallaby release

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 Ch04] Typo's, spelling, language corrections

---

doc/common/glossary.md
doc/ref_arch/openstack/chapters/chapter01.md
doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md
doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_arch/openstack/chapters/chapter06.md
doc/ref_arch/openstack/chapters/chapter07.md
doc/ref_arch/openstack/chapters/chapter08.md

Fixes #2497 
Changes to common/glossary; and RA-1 chapters
Delete bogometers
use of the terms _instances_ and _servers_ as appropriate

[RA-1 All] Introduce OpenStack "server" concept

---

doc/ref_arch/kubernetes/chapters/chapter07.md

fixes #2612
I'm not actually sure if it's better to remove the version rather than refresh it and update it at every release.
This could be done whilst checking if open issues are still valid and relevant at each release of Anuket.

clean up chapter 7 and remove hardcoded versions

---

doc/ref_arch/openstack/chapters/chapter02.md

Tables headers harmonisation
Alignment with RM
Typos 
References added

[RA1 Ch02] Proofreading

---

doc/ref_arch/kubernetes/chapters/chapter04.md

Fixes #2700 
Corrected link
minor typos

[RA2 Ch04] Proofreading 4.6 - 4.10

---

doc/ref_impl/cntt-ri2/chapters/chapter01.md
doc/ref_impl/cntt-ri2/chapters/chapter02.md

[RI2] Harmonizing capitalization - huge pages

---

doc/ref_model/chapters/chapter08.md

[RM Chap8] Proofreading
Update:
Align and update Table Numbering so it is consistent with rest of document (table numbers on bottom)

[RM Chap8] Proofreading

---

doc/ref_arch/openstack/README.md

Update Release BUndle and chapter staus

[RA1 README] Release version

---

doc/ref_impl/cntt-ri2/chapters/chapter01.md
doc/ref_impl/cntt-ri2/chapters/chapter02.md
doc/ref_impl/cntt-ri2/chapters/chapter03.md
doc/ref_impl/cntt-ri2/chapters/chapter04.md
doc/ref_impl/cntt-ri2/chapters/chapter05.md

Partially closes #2603
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

[RI2] proofreading and removal of some HTML tags

---

doc/ref_arch/kubernetes/chapters/chapter06.md

Closes #2598 , Closes #2599 , Closes #2600 , Closes #2601 , Closes #2602 
Added the storage volumes and node ephermeral storage tests

[RA2 Ch6] sync features with SIG tables

---

doc/ref_arch/kubernetes/chapters/chapter06.md

[RA2 Ch06] Fix description of Feature:NodeAuthorizer in section 6.4

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

[RI1] Harmonizing capitalization - huge pages

---

doc/common/glossary.md

[Common, Glossary] Harmonizing capitalization - huge pages

---

doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter04.md

[RA1] Harmonizing capitalization - huge pages

---

doc/ref_cert/RC1/chapters/chapter02.md

It's basic markdown fixes but it blocks the RST conversion

[nit] Fix blank lines in RC1

---

doc/ref_cert/RC2/chapters/chapter01.md
doc/ref_cert/RC2/chapters/chapter03.md

Else the RST conversion basically fails.

[RC2] dos2unix chapter01.md and chapter03.md

---

doc/ref_cert/RC1/chapters/chapter05.md

Else it fails the RST conversion.

[RC1] Make title level consistents

---

doc/ref_cert/RC1/chapters/chapter05.md
doc/ref_cert/RC1/chapters/chapter07.md

It basically fails the RST conversion as it's incorrect.

[RC1] Add alt text in all image links

---

doc/ref_impl/cntt-ri2/README.md

[RI2] Update README for Lakelse

---

doc/ref_cert/RC2/README.md
doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter04.md

detected by sphing linkcheck when converting to rst.

[nit] fix falsy links

---

doc/ref_cert/RC1/README.md
doc/ref_cert/RC1/chapters/chapter01.md
doc/ref_cert/RC1/chapters/chapter02.md
doc/ref_cert/RC1/chapters/chapter03.md
doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC1/chapters/chapter05.md
doc/ref_cert/RC1/chapters/chapter06.md
doc/ref_cert/RC1/chapters/chapter07.md
doc/ref_cert/RC1/chapters/chapter08.md

It's a key fix prior to rst conversion.

Fix links and remove bogometers

---

doc/ref_cert/RC1/chapters/chapter01.md
doc/ref_cert/RC1/chapters/chapter02.md
doc/ref_cert/RC1/chapters/chapter03.md
doc/ref_cert/RC1/chapters/chapter05.md
doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter04.md

[RC1][RC2] Update all RTD links to stable-lakelse

---

doc/ref_arch/kubernetes/README.md
doc/ref_arch/openstack/README.md
doc/ref_cert/RC1/README.md
doc/ref_cert/RC2/index.rst

Update RC1 & RC2 bundles

---

doc/ref_cert/RC1/README.rst
doc/ref_cert/RC1/chapters/chapter04.rst

It allows browsing our doc via Github as CNTT actors may do.

Symlink README.rst to index.rst (#2755)

---

doc/ref_cert/RC1/conf.py

[RC1] nit: fix conf.py

---

doc/ref_cert/RC1/chapters/chapter01.md
doc/ref_cert/RC2/chapters/chapter01.md

It was detected when converting to RST [1][2].
[1] https://github.com/cntt-n/CNTT/issues/2758
[2] https://github.com/cntt-n/CNTT/pull/2762

[RC1][RC2] Avoid duplicating introduction

---

.readthedocs.yaml

See https://readthedocs.org/projects/cntt/builds/15541950/

[COMMON] Put rtd settings in tree

---

doc/conf.py
test-requirements.txt

Exclude .tox directories in Sphinx conf.py

---

doc/ref_model/README.md

[RM README] Lakelse Release Date Correction

---

doc/ref_model/chapters/chapter02.md

Fixes #2773
Second Figure 2-1 in Section 2.4 Profiles, Profile Extensions & Flavours renumbered Figure 2-5 including in text.

[RM Ch02] Second Figure 2-1 correction

---

doc/ref_model/README.md

[RM README] Update Status and TOC with Appendix

---

doc/ref_arch/openstack/chapters/README.rst
doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter05.rst
doc/ref_arch/openstack/chapters/chapter06.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/chapters/chapter08.rst

RST file creation with pandoc
Md references will be addressed in another subsequent PR

[RA1] RST files uploaded

---

doc/ref_arch/openstack/chapters/chapter05.rst

Addition of backslashes for cut words

[RA1 Ch05] RST conversion: corrections

---

doc/ref_arch/openstack/chapters/chapter07.rst

Removal of duplicated title for figure 7-1

[RA1 Ch07] RST conversion: correction

---

doc/ref_arch/openstack/chapters/chapter08.rst

Numbering removed for internal link

[RA1 Ch08] RST conversion: correction

---

doc/ref_arch/openstack/chapters/chapter06.rst

Internal links modified: incomplete links and numbering removal
"Patches" : table fixed

[RA1 Ch06] RST conversion: corrections

---

doc/ref_cert/RC1/conf.py
doc/ref_cert/RC1/test-requirements.txt

[RC1] Switch to Sphinx Material

---

doc/ref_arch/openstack/chapters/chapter02.rst

Addition of backslashes to fix cut words

[RA1 Ch02] RST conversion: corrections

---

doc/ref_cert/RC1/chapters/chapter01.rst
doc/ref_cert/RC1/chapters/chapter02.rst
doc/ref_cert/RC1/chapters/chapter04.rst
doc/ref_cert/RC2/chapters/chapter04.rst

It also improves links by leveraging intersphinx mapping.

[RC1] Fix all dead links

---

doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter06.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/conf.py
doc/ref_arch/openstack/test-requirements.txt
doc/ref_arch/openstack/tox.ini

At the time of writting, tox will fail because of pending RST issues.

[RA1] Publish doc build files

---

doc/ref_model/chapters/chapter09.rst

As the new structure of the section 9.5.1 Infrastructure LCM Automation will be created along the lines decided at the RM Meeting on 24 Feb.  Contents 9.5.1 is initially discussed in RM meetings and in Wiki page (https://wiki.anuket.io/display/HOME/Infrastructure+LCM+Automation) we delete empty sections:
9.5.1.1. Hardware Configuration CI/CD
9.5.1.2. Networking Automation
9.5.1.3. Software Development CI/CD1.

[RM Ch9.5.1] structure changes

---

doc/ref_model/chapters/appendix-a.rst

[RM Appendix]: Adding reference to RM Chapter 7.5

---

doc/ref_model/chapters/chapter04.rst

Fixes #2717 
Comment off contentless "Exposed Infrastructure Performance Measurements" section

[RM Ch04] Exposed Infrastructure Performance Measurements

---

doc/ref_cert/RC1/test-requirements.txt
doc/ref_cert/RC2/conf.py
doc/ref_cert/RC2/test-requirements.txt
doc/ref_cert/conf.py
doc/ref_cert/test-requirements.txt

It also modifies boot RC2 and RC root themes

Complete Sphinx material migrations

---

doc/ref_cert/RC1/conf.py
doc/ref_cert/RC2/conf.py
doc/ref_cert/conf.py

Enable numfig

---

doc/ref_model/chapters/appendix-a.rst
doc/ref_model/chapters/chapter04.rst

The individual build of RM is currently broken due to errors uncovered
by link checks and RST linting.
Fixes #2886
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

[RM] fixing broken individual build

---

doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC2/chapters/chapter01.rst

Remove useless labels added by hand

---

doc/ref_cert/RC1/chapters/chapter07.rst

[RC1] Updates vnf-sdk-marketplace

---

doc/ref_model/chapters/chapter04.rst
doc/ref_model/chapters/chapter05.rst
doc/ref_model/chapters/chapter06.rst
doc/ref_model/chapters/chapter08.rst
doc/ref_model/chapters/chapter09.rst

[RM] Fix all figures

---

doc/ref_arch/openstack/chapters/chapter02.rst

[RA1] Wrap chapter2 tables

---

doc/ref_cert/index.rst

These job links no longer exist since Airship is being archived.

[RC] Remove airship links

---

doc/ref_model/chapters/chapter01.rst

[RM Ch1]: Linewrap to 120 chars

---

doc/ref_arch/kubernetes/chapters/chapter05.rst

[RA2 Ch5]: Linewrap to 120 characters

---

doc/ref_cert/RC1/chapters/chapter03.rst

[nit] Fix one blank char

---

doc/ref_model/chapters/chapter07.rst

[RM Ch7]: Linewrap to 120 chars

---

doc/ref_arch/openstack/chapters/chapter02.rst

Fixes #2937 
Also fixed some other typo's

[RM Ch02] Remove duplicated title4 #2937

---

doc/ref_arch/openstack/chapters/chapter02.rst

[RA1 Ch02] Tables wrap (continued)

---

doc/ref_cert/RC2/tox.ini

Prepare RC2 PDF builds

---

doc/ref_model/chapters/appendix-a.rst

[RM Appendix]: linewrap to 120 chars

---

doc/ref_model/chapters/chapter10.rst

[RM Ch10]: linewrap to 120 chars

---

CODEOWNERS

this is to add owners to all index files and miscellaneous

add all project leads to CODEOWNERS

---

doc/ref_model/chapters/chapter09.rst

[RM Ch9]: linewrap to 120 chars

---

doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/chapters/chapter04.rst
doc/ref_cert/RC1/chapters/chapter05.rst

[RC1] Avoid useless redirect urls

---

doc/ref_model/chapters/chapter07.rst

Section dealing with regulatory frameworks: role in general and examples form few jurisdictions, to be extended in future releases.

[RM Ch 07] Cloud Infrastrucure Regulatory Compliance 

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

[RA2 ch2] edge cloud requirements to ra2

---

doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst

[RA1 Ch03/04] Cloud Deployment Model + Table Formats

---

doc/ref_arch/openstack/chapters/chapter03.rst

Fixes issue #2787  and #2860
Alignment with RM on storage

[RA1 Ch03] Storage, alignment with RM

---

doc/ref_model/chapters/chapter04.rst

Fixes issue #2896
Per ETSI GS NFV-TST 008 document, table 4-8 completed

[RM Ch04] Internal Performance Metrics

---

doc/ref_model/chapters/chapter07.rst
doc/ref_model/chapters/chapter08.rst

Fixes issue#2828
In addition: typos, titles changed

[RM Ch07&08] GSMA FS40 doc updated

---

doc/ref_model/chapters/chapter07.rst

[RM Ch07] SBOM content added

---

doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter07.rst

Fixes issues #2776 and #2238
Chapter 7:
addition to the provisioning of underlying resources
addition on VIM deployment, installers
Chapter4:
Reference to chapter 7 to installers

[RA1 Ch07] Automation and installers

---

doc/ref_impl/cntt-ri2/chapters/chapter01.rst
doc/ref_impl/cntt-ri2/chapters/chapter02.rst
doc/ref_impl/cntt-ri2/tox.ini

This PR wraps the last remaining lines (requirements table in ch02)
to 120 characters. It also enforces checking of the 120 character
line length limit at build time.
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

[RI2] Wrapping all lines to 120 chars and enforcing checks

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

[Based on the analyzis of CNCF CNF Testsuite](https://wiki.anuket.io/display/HOME/2022/03/01/Analyzis+of+CNCF+CNF+Testsuite+tests+for+RA2).
Closes #2909

[RA2 Ch4]: Adding workload requirements

---

doc/ref_cert/RC2/chapters/chapter01.rst
doc/ref_cert/RC2/chapters/chapter02.rst
doc/ref_cert/RC2/chapters/chapter04.rst
doc/ref_cert/RC2/conf.py
doc/ref_cert/RC2/index.rst

It also formats tables and fixes duplicated title.
It cleans bundle data which are manually removed by GSMA.

[RC2] Fix PDF rendering issues

---

doc/ref_model/chapters/chapter07.rst
doc/ref_model/chapters/chapter08.rst
doc/ref_model/conf.py
doc/ref_model/tox.ini

It fixes wrong urls detected by linkcheck.
It stops checking GSMA urls as GSMA asks for auth.
nplang.org is currently unchecked because the website is
temporarily down "Sucuri Website Firewall - Not Configured"
closes: #2996

[RM] Fix rm links

---

doc/ref_arch/openstack/chapters/chapter02.rst

[RA1] Allow passing the gate

---

doc/ref_model/chapters/chapter01.rst

[RM] nit: explicit markup ends without a blank line; unexpected unindent

---

doc/ref_arch/openstack/chapters/chapter02.rst

Fixes issue#2732
Internal links added into requirements table 
Bold characters for must key words
Correction of links (2 lines links)

[RA1 ch02] Specification references added

---

doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/conf.py

[RA1] Fix figure refs and definitions

---

doc/ref_cert/RC1/chapters/chapter02.rst
doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/chapters/chapter04.rst
doc/ref_cert/RC1/chapters/chapter05.rst
doc/ref_cert/RC1/chapters/chapter08.rst
doc/ref_cert/RC1/conf.py
doc/ref_cert/RC1/index.rst

[RC1] Fix PDF rendering issues

---

doc/ref_model/conf.py

It's part of a bigger change splitting doc.

[RM] Export title4 for RA1

---

doc/ref_arch/openstack/tox.ini

[RA1] nit: fix last false external lookup

---

doc/ref_cert/RC1/chapters/chapter02.rst
doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/chapters/chapter05.rst
doc/ref_cert/RC1/chapters/chapter08.rst

Remove all false external lookups

---

doc/ref_cert/RC2/chapters/chapter02.rst
doc/ref_cert/RC2/chapters/chapter04.rst

This file is no longer exported.

[RC2] Stop leveraging README

---

doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter06.rst

:doc: asks for an external lookup which is false here.

[RA1] Remove falsy external docs

---

doc/ref_model/chapters/chapter02.rst
doc/ref_model/chapters/chapter03.rst
doc/ref_model/chapters/chapter04.rst

[RM] Fix Figure definitions and refs

---

doc/common/abbreviations.rst

[nit][bug] Fix incorrect table

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

[ra2 ch4] fix ch4 build errors

---

doc/ref_arch/kubernetes/tox.ini

update ra2 tox to add -keep-going and linkcheck

[ra2] update ra2 tox to add -keep-going and linkcheck

---

doc/ref_arch/kubernetes/chapters/chapter03.rst

[RA2 Ch3]: Correction of linter errors

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

[RA2 Ch2]: Correction of linter errors

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst

changing all :doc: and :ref: to the same format:
```
:ref:`absolute/path:section/`
```
I didn't find any references in chapters 4 to the end

[RA2 CH1-3] fix ra2 :refs:

---

tox.ini

Add test-requirements for CNTT RTD

---

doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/conf.py
doc/ref_impl/cntt-ri/chapters/chapter01.rst
doc/ref_impl/cntt-ri2/chapters/chapter01.rst
doc/ref_model/chapters/chapter03.rst
doc/ref_model/chapters/chapter07.rst

It completes the PR changing RTD design.

Fix latest incorrect refs

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst
doc/ref_arch/kubernetes/chapters/chapter07.rst
doc/ref_arch/kubernetes/conf.py

It completes the full RTD migration.

[RA2] Leverage internal links when possible

---

doc/ref_impl/cntt-ri/chapters/chapter03.rst
doc/ref_impl/cntt-ri/conf.py

[RI1] Switch to intersphinx ref for all CNTT link

---

doc/ref_arch/kubernetes/README.rst

[RA2 Readme]: Fixing Appendix reference in the chapter list

---

doc/conf.py
doc/ref_arch/kubernetes/conf.py
doc/ref_arch/openstack/conf.py
doc/ref_cert/RC1/conf.py
doc/ref_cert/RC2/conf.py
doc/ref_cert/conf.py
doc/ref_impl/cntt-ri/conf.py
doc/ref_impl/cntt-ri2/conf.py
doc/ref_model/conf.py

Select the right moselle intersphinx

---

doc/ref_arch/openstack/README.rst
doc/ref_cert/RC1/index.rst
doc/ref_cert/RC2/index.rst

[RC1][RC2][RA1] Use :numbered: in all stream toc

---

doc/ref_arch/openstack/chapters/chapter03.rst

it breaks the PDF build
https://build.opnfv.org/ci/job/cntt-tox-ra1/1542/console

[RA1] Fix Foot note

---

doc/common/references.rst
doc/gov/chapters/chapter09.rst
tox.ini

It fixes one of the last 2 RST issues (duplicated)
Please note that [NI3] et [NI4] are still equal

Merge the duplicated security table

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

Fix manual merge conflict error

---

doc/ref_cert/RC1/chapters/chapter02.rst

[RC1][nit] fix duplicated `

---

doc/ref_arch/kubernetes/chapters/chapter03.rst

[RA2] Fix one ref minor issue

---

doc/ref_cert/RC1/chapters/chapter02.rst
doc/ref_cert/RC1/chapters/chapter05.rst

[RC1] Leverage note directive

---

doc/gov/README.rst
doc/index.rst
doc/ref_arch/kubernetes/README.rst
doc/ref_impl/cntt-ri/index.rst
doc/ref_impl/cntt-ri2/index.rst
doc/ref_model/README.rst

[all]: Centralize release and release history

---

doc/ref_arch/openstack/README.rst
doc/ref_arch/openstack/conf.py

Based on the discussion in #3045

[RA1]: Correcting document title

---

doc/ref_arch/openstack/chapters/chapter08.rst
doc/ref_arch/openstack/chapters/chapter09.rst
doc/ref_arch/openstack/conf.py

Targeting the next GSMA RA1 updates, it extracts a part of:
- RC/index.rst
- RC1/chapters/chapter03
- RC1/chapters/chapter04

[RA1][RC1] Dump RC1 in RA1 Chapter5

---

doc/ref_arch/openstack/chapters/chapter01.rst

[RA1 Ch01] Abbreviations table added

---

doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst

Titles changed to keep unique titles  
1 link in chapter 4 to chapter 3 fixed

[RA1 Ch03 Ch04] Titles made unique

---

doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst

Fix a few incorrect refs

---

doc/ref_arch/openstack/chapters/chapter01.rst

[RA1 Ch01] Acronyms added

---

doc/ref_arch/openstack/chapters/chapter01.rst

Fixes issues #3105 and #3135 
Addition of architectural principles from Common 
Review of document organisation : for Chapters 8 and 9

[RA1 Ch01] Principles & doc organisation

---

doc/ref_arch/openstack/chapters/chapter08.rst

It completes "RA1 Ch08] Review of Conformance's
chapter (#3139)"

[RA&] Fix minor rst issues

---

doc/ref_arch/openstack/chapters/chapter08.rst
doc/ref_arch/openstack/refs.bib

[RA1] Add biblio for chapter 8

---

doc/ref_arch/openstack/chapters/chapter08.rst

[RA1] Fixed a unsolved merge conflict

---

doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/chapters/chapter08.rst

Some typos: z changes to s in Chapter 1, 7, and 8

[RA1] Typos British English

---

doc/ref_arch/openstack/chapters/chapter01.rst

Solve language issues
Fixes issue #3149

[RA Ch01] Text revised

---

doc/ref_arch/openstack/chapters/chapter05.rst
doc/ref_arch/openstack/refs.bib

Add all Chapitre5 links to biblio

---

README.rst
doc/ref_impl/cntt-ri/tox.ini

It also adds upper constraints when verifying ri1.

Fix false hardcoded url in README.rst

---

doc/ref_model/chapters/chapter03.rst

[RM Ch03] Change openconfig link Issue #3151

---

doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter08.rst
doc/ref_arch/openstack/chapters/chapter09.rst
doc/ref_arch/openstack/conf.py
doc/ref_arch/openstack/refs.bib
doc/ref_arch/openstack/test-requirements.txt
doc/ref_arch/openstack/togsma.py
doc/ref_arch/openstack/tox.ini

It also moves bibliography at the end and
formats refs.bib.

[RA1] Convert bibtex to tables for GSMA

---

doc/ref_arch/openstack/tox.ini

[nit] call new py script

---

doc/common/chapter00.rst
doc/ref_arch/openstack/chapters/chapter01.rst

[RA1, Common] Architectural Principles

---

doc/ref_cert/RC2/conf.py
doc/ref_cert/RC2/index.rst

Based on the discussion in #3045

[RC2]: Correcting the title of the document

---

doc/ref_arch/openstack/chapters/chapter08.rst

It also precises the main API requirements in tc mapping
open-source VNF onboarding and testing, and API benchmarking also cover a subset of the APIs.

Proof reading RA1 Chapter8

---

doc/ref_cert/RC2/index.rst

nit: Fix #3118

---

doc/ref_arch/openstack/togsma.py

Nit: first ref is [1]

---

doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter06.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/chapters/chapter08.rst

Comment off the empty Tenenat Recommendations table

[RA1 Ch[02-08]] Typo, grammar and empty tables

---

doc/ref_arch/openstack/refs.bib

Refs.bib file
Non used references removed
References reordered per chapter

[RA1 Refs] References sorted and reordered

---

doc/ref_arch/openstack/chapters/chapter05.rst

Pandoc fails when blank chars in cells then it
breajs tge full GSMA process.

Switch to list table

---

doc/ref_cert/RC2/tox.ini

Update to latest OpenStack stable upper constraints

---

doc/ref_arch/openstack/chapters/chapter02.rst

It basically removes it which let the docs unchanged.

Remove former md bookmark.

---

doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter06.rst
doc/ref_arch/openstack/chapters/chapter08.rst
doc/ref_cert/RC2/chapters/chapter02.rst

é in spécial is allowed in chapter01.rst

Remove all non ascii chars

---

doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter07.rst

[RA1] Switch to en_GB (Sphinx spellcheck)

---

doc/ref_model/chapters/chapter09.rst

This PR responds to Issue#3088, point 1:
Move resource lifecycle model to the top of the section (after Introduction)

[RM Ch09] Chapter restructure 1

---

doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter02.rst

Transform all must to **MUST**

---

doc/ref_model/chapters/chapter08.rst

Add "Manage Catalog" interaction into the model.
This update includes updates figure references.
The figure updates are separately (and individually) uploaded.
To avoid reference issue, the related figure update pull requests should be approved prior to accepting this change.
Related figure pull requests:
- https://github.com/cntt-n/CNTT/pull/3089
- https://github.com/cntt-n/CNTT/pull/3090
- https://github.com/cntt-n/CNTT/pull/3091
- https://github.com/cntt-n/CNTT/pull/3092
- https://github.com/cntt-n/CNTT/pull/3093

[RM Chap8] Hybrid Multi-Cloud - Multi-Cloud Interactions Model - Add Manage Catalog

---

doc/ref_impl/cntt-ri/conf.py
doc/ref_impl/cntt-ri/index.rst

Based on the discussion in #3045

[RI1][pcac]: Correcting document title

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

[ra2] clarify gen.cnt.04

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

[ra2] clarify inf.ntw.02

---

doc/ref_model/chapters/chapter08.rst

[RM Chap8] Multi-Cloud Interactions Model - Diagram Reference Update
Update the: Multi-Cloud Interactions Model "Simple Stereotypes" so it refers to correct diagram (03) with addition of "catalog"

[RM Chap8] Multi-Cloud Interactions Model - Diagram Reference Update

---

doc/ref_model/chapters/chapter09.rst

Comment on difference between models in Ch8 (cloud consumption) and Ch9 (cloud build/operate)

[RM Ch09] Comparison of lifecycle model to consumption model of Ch8

---

doc/ref_model/chapters/chapter08.rst

This PR is a response to Issue#3136, and provides a comparison of two models: consumption model in Chapter 8, and build/operate model in Chapter 9

[RM Ch08] Model comparison with chapter 9

---

doc/ref_model/chapters/chapter07.rst

Fixes issue#3247
References added: NIST-800-218 and GSMA FS.16

[RM Ch07] Security references added

---

doc/ref_model/chapters/chapter03.rst

This PR replaces PR #3259 (since I cannot modify it probably because I didn't proceed correctly)
It is a minimal description of the energy efficiency for explaining the related metrics added by PR #3258 for fixing Issue #3223. It may need to be further completed

[RM Ch03] Add energy efficiency v2

---

doc/ref_model/chapters/chapter04.rst

[RM Ch04] Add energy measurement capabilities

---

doc/ref_model/chapters/chapter08.rst

[RM Chap8] Multi-Cloud Interaction Model - Manage Catalog
Make explicit that responsibility for creation and publication of Catalog is with the Service Provider.

[RM Chap8] Multi-Cloud Interaction Model - Manage Catalog

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

Based on the agreement with CNCF CNF Testbed documented in here: https://wiki.anuket.io/display/HOME/2022/03/01/Analyzis+of+CNCF+CNF+Testsuite+tests+for+RA2

[RA2Ch4]: Adding app requirements

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

Based on the suggestion of @wavell and @denverwilliams.

[ra2ch4]: Small language tweeks of Chapter 4.2

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

fixes #2788 
adding requirements for Kubernetes infrastructure monitoring

[ra2] add Cloud Infrastructure Monitoring Capabilities

---

doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/refs.bib

[RA1 CH04] Update Cyborg accelerators drivers

---

doc/ref_model/chapters/chapter01.rst
doc/ref_model/chapters/chapter03.rst
doc/ref_model/chapters/chapter04.rst
doc/ref_model/chapters/chapter08.rst
doc/ref_model/refs.bib

During the implementation of #3260 several bugs were introduced. This pr fixes these errors.
Please do not merge without testing if the build succeeds.

[RM]: Fixing bugs of pr #3260

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

[ra2 ch2] nile proofreading

---

doc/ref_arch/kubernetes/chapters/chapter03.rst

[ra2 ch3] nile proofreading

---

doc/ref_arch/kubernetes/chapters/chapter05.rst

[RA2 Ch5]: Nile proofreading changes

---

doc/ref_arch/kubernetes/chapters/chapter06.rst

[ra2 ch6] nile proofreading

---

doc/ref_arch/kubernetes/chapters/chapter07.rst

[ra2 ch7] nile proofreading

---

doc/ref_impl/cntt-ri2/chapters/chapter02.rst

Signed-off-by: zhuguanyu <zhuguanyu5@huawei.com>

[RI2 Ch2]: Update RI2 requirements based on RA2 Moselle (#3283)

---

doc/common/references.rst
doc/conf.py
tox.ini

It also updates requirements and py version
as the other doc verifications

Fix a few links in gov

---

doc/ref_impl/cntt-ri2/chapters/chapter04.rst

Signed-off-by: zhuguanyu <zhuguanyu5@huawei.com>

[RI2 Ch04] Update runbook installation on provider infrastructure

---

doc/index.rst

Adding Nile to the release list of the start page

[root]: Adding Nile release to the start page

---

doc/ref_model/chapters/chapter02.rst

[RM Ch02] 6G Related Use Cases

---

doc/ref_model/chapters/chapter08.rst

This reverts commit 192ee8afb434bf84c56828145d3a65b8da38e233.

Revert "[RM Ch08] Orchestration support for 6G Use cases (#3254)"

---

doc/ref_arch/openstack/conf.py
doc/ref_arch/openstack/test-requirements.txt
doc/ref_cert/RC2/conf.py
doc/ref_cert/RC2/test-requirements.txt
doc/ref_cert/conf.py
doc/ref_cert/test-requirements.txt

[RA1][RC2] Switch to Piccolo Sphinx theme

---

doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/chapters/chapter06.rst

[RA2 Ch4 Ch6] fix API rule to include alpha/beta mandatory specs

---

doc/ref_model/chapters/chapter07.rst

[RM Ch7] Security HW Assist for Data in Use

---

doc/ref_arch/kubernetes/chapters/chapter07.rst

[RA2] Update chapter07.rst

---

doc/ref_arch/kubernetes/README.rst
doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst

[ra2 ch1] add principles, terminology and abbreviations for GSMA

---

doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/refs.bib

Keeping the CNF requirements harmonized to CNF Conformance.
Fixes #3312 
Implementing changes proposed in here: https://wiki.anuket.io/display/HOME/2023/04/25/Analyzis+of+CNCF+CNF+Conformance%2C+RA2+and+RC2+CNF+tests

[RA2 Ch4]: Update CNF requirements

---

doc/ref_cert/RC2/chapters/chapter04.rst

Synchronizing RC2 with #3352 
Work wiki: https://wiki.anuket.io/display/HOME/2023/04/25/Analyzis+of+CNCF+CNF+Conformance%2C+RA2+and+RC2+CNF+tests

[RC2 Ch4]: Update CNF tests

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst

[RA2 Ch1-2-3] Proofreading Ch1-2-3

---

doc/ref_arch/kubernetes/chapters/chapter01.rst

- Terms list converted to table
- Name of abbreviations table columns updated
Fixes #3375

[RA2 Ch1]: Modifying structure for GSMA

---

doc/ref_model/chapters/chapter09.rst

RM minor typos corrected Update chapter09.rst

---

doc/ref_model/chapters/chapter02.rst

Several minor typos corrected.

RM minor typos Update corrected chapter02.rst

---

doc/ref_model/chapters/chapter03.rst

RM minor typos corrected Update chapter03.rst

---

doc/ref_model/chapters/chapter04.rst

RM minor typos corrected Update chapter04.rst

---

doc/index.rst

Also correcting the release date of Orinoco

Adding Pieman release information
