anuket-project/anuket-specifications

doc/ref_model/chapters/chapter04.md

Changed "Infrastructure profiles catalog" to "Infrastructure instances catalog" for consistency with other changes.
Section 4.3 Storage extensions: corrected spelling -- "Multiple" instead of "Multiplee."

Chapter 04 (minor edits) 

---

doc/ref_model/chapters/chapter01.md

Made changes to some of the terms.
Still need to be resolved:
1. Do Instance Types include sizing (number of CPUs, RAM, etc.) information or are they just the Basic, Network-Intensive, etc. Types?  
2. Still need to fix the SW/HW Profile and Configuration terms.

Chapter 01 (Terminology fixes)

---

README.md
doc/ref_arch/README.md
doc/ref_arch/kubernetes/chapters/chapter01.md
doc/ref_arch/kubernetes/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter01.md
doc/ref_arch/openstack/chapters/chapter02.md
doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md
doc/ref_impl/chapter02.md
doc/ref_impl/cntt-ri/chapters/chapter01.md
doc/ref_model/chapters/chapter01.md
doc/ref_model/chapters/chapter02.md
doc/ref_model/chapters/chapter03.md
doc/ref_model/chapters/chapter04.md
doc/ref_model/chapters/chapter05.md
doc/ref_model/chapters/chapter06.md
doc/ref_model/chapters/chapter07.md
doc/ref_model/chapters/chapter08-annex.md
doc/ref_model/chapters/chapter08.md
doc/ref_model/chapters/chapter09.md

It partially fixes #303 [1] ("R2 Line has trailing whitespace").
It also modifies one typo (definitions)
[1] https://github.com/cntt-n/CNTT/issues/303

Delete all trailing whitespaces

---

doc/ref_arch/openstack/chapters/chapter04.md
doc/ref_model/chapters/chapter04.md
doc/ref_model/chapters/chapter08-annex.md
doc/ref_model/chapters/chapter08.md

It replaces flavor by flavour and behavior by behaviour.
It's worth mentioning that they are cases where flavor makes sens even
if en_GB is selected (e.g. the OpenStack resources [1])
[1] https://docs.openstack.org/nova/latest/user/flavors.html

Replace a few American spelling words

---

doc/ref_model/chapters/chapter08-annex.md

Removed specific values to generalize annex. Also replaced html with git style markdown.
Issue: https://github.com/cntt-n/CNTT/issues/270

Kagreenwell issue 270 patch

---

doc/ref_impl/cntt-ri/README.md

delete the wrong infomation about CNTT-RI project in OPNFV

[RI 1 Core] Change the RI page

---

doc/ref_arch/openstack/chapters/chapter05.md

It sets qos, trunk and metring as mandatory.
More details in [1]
[1] https://gerrit.opnfv.org/gerrit/c/functest/+/68668

[RA-1 Chapter 05] Add a new API tab about Neutron extensions

---

doc/ref_arch/openstack/chapters/chapter05.md

It completes the previous section by adding the minimal microversion
API and the Cinder features required:
- backup
- snapshot
- clone
- manage_snapshot
- manage_volume
- volume_revert
Closes: #437

[RA-1 Ch05] Add Cinder Microversions and Features in API

---

doc/ref_arch/openstack/chapters/chapter05.md

It sets mandatory Keystone features and then precises the API
available.
Fixes #624

[RA1 Ch05] Update Keystone API

---

doc/ref_arch/openstack/chapters/chapter05.md

It sets mandatory Swift features and then precises the API
available.
Fixes #626

[RA1 Ch05] Update Swift API

---

doc/ref_arch/openstack/chapters/chapter05.md

v2.5 is more precised than v2.0
https://docs.openstack.org/api-ref/image/versions/index.html#api-versions
Fixes #647

[RA1 Ch05] Precise Glance versions

---

doc/ref_impl/cntt-ri/chapters/chapter04.md

Per the discussions on the [OPNFV Infra Wiki](https://wiki.opnfv.org/display/INF/CNTT+RI+Lab+Infrastructure+Discussion) and the Infra WG meetings, these changes aim to update the hardware requirements for Release 1 of the Reference Implementation to those needed to support the Airship installer and other basic OpenStack deployments.

[RI1 Ch04] Update Reference Implementation Lab Hardware

---

doc/ref_arch/openstack/chapters/chapter05.md

Ceph is selected but doesn't support "attach_encrypted_volume".
Then it sets the feature as optional which will may be listed in gaps.
enable_instance_password is part of testing configuration.

[RA 1] Fix Nova features tab

---

doc/ref_arch/openstack/chapters/chapter05.md

Fixes #732 
As a result of the decision taken during RA #1 meeting (October 25), remove Ironic APIs, for the 2 following reasons: Ironic is an optional service and Ironic APIs are not called directly.
5.2 ->Section about Ironic removed
5.3 -> Lines about Ironic removed from  API and CLI tables

[RA1 Ch05] Remove Ironic APIs

---

doc/ref_arch/openstack/chapters/chapter04.md

[RA-1 Ch04] Update Ironic writeup. Added, "As Ironic is currently not invoked directly (only invoked through other srevices such as Nova) hence its APIs will not be specified." to Note in 4.3.1.7.
Fixes #734

[RA-1 Ch04] Update Ironic writeup

---

CONTRIBUTING.md

[Technical Steering] Updating Contribution process as per TSC call

---

doc/ref_arch/openstack/chapters/chapter02.md

Changed:
| req.vim.04 | General | The Architecture must support Enhanced Platform Awareness (EPA). |
|--------|------|------------|
| `req.vim.04` | General | The Architecture **must** support Enhanced Platform Awareness (EPA) only for discovery of infrastructure resource capabilities.|
Fixes #792

[RA-1 Ch02] EPA requirement

---

doc/ref_model/chapters/chapter05.md

Fixes #521 
The initial definition "Binding of a process to a dedicated CPU" doesn't take into account cores and SMT.
It is changed by:
"Binding a vCPU to either a physical core or a thread of a core with SMT"

[RM Ch05] Modification of CPU pinnnig definition

---

doc/ref_cert/lfn/chapters/chapter04.md

It adds 4.3.5 opensource VNF onboarding and testing describing the
test cases executed by CNTT compliance containers in Functest [1].
Closes: #856
[1] https://lists.opnfv.org/g/opnfv-tsc/message/5717

[RC1] Add opensource VNF onboarding and testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Glance testing in RC1 4.3.4.2.
Closes: #832

[RC1] Fill Glance testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It describes Cinder testing in RC1 4.3.4.3.
Closes: #836

[RC1] Fill Cinder testing

---

doc/ref_cert/lfn/chapters/chapter04.md

It adds 4.3.5 OpenStack API benchmarking describing the scenarios
executed by CNTT-API compliance containers in Functest [1].
[1] https://lists.opnfv.org/g/opnfv-tsc/message/5717

[RC1] Add OpenStack API benchmarking

---

doc/ref_cert/lfn/chapters/chapter04.md

It adds 4.3.5 Dataplane benchmarking describing the test cases
executed by CNTT compliance containers in Functest [1].
Closes: #851
[1] https://lists.opnfv.org/g/opnfv-tsc/message/5717

[RC1] Add dataplane benchmarking

---

doc/ref_cert/lfn/chapters/chapter02.md

It highlights that RI and RC should use the same CI toolchain.
In case if RC, it leverages on local components but the interfaces
remain unchanged.
Fixes: #868

[RC1] Detail CNTT RI and RC toolchains

---

doc/ref_cert/lfn/chapters/chapter04.md

It leverages on relative_url filter [1] as proposed by Jekyll
[1] https://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/

[RC1] Fix broken links due to baseurl (/CNTT) set by GitHub

---

doc/ref_cert/lfn/chapters/chapter09.md

It describes how to deploy the CI toolchain checking CNTT Compliance
as announced by [1].
At the time of writing, the CI description file lists all the
mantory containers (see RM/RA-1 Requirements).
It depends on the next 2 PRs:
- https://github.com/cntt-n/CNTT/pull/867
- https://github.com/cntt-n/CNTT/pull/870
[1] https://lists.opnfv.org/g/opnfv-tsc/message/5717
Fixes: #872

[RC1] Add RC Cookbook

---

doc/ref_arch/kubernetes/chapters/chapter02.md

This change introduces a requirements matrix for Reference Architecture 2.
It contains a list of attributes defined in the Reference Model and states if
RA2 supports them or not.
Fixes #736

[RA2 Ch02] Requirements matrix for RA2

---

doc/ref_cert/lfn/chapters/chapter08.md

It takes the last backports into account to fit CNTT needs.

[RC1] List all Functional testcases offered by Functest Hunter

---

doc/ref_arch/kubernetes/chapters/chapter08.md

Fixes #397 
Fixes #398 
Fixes #399 
Fixes #400 
Fixes #599  
This is to look at the southbound interfaces towards the infrastructure resources.

[RA2 Ch08] Initial content for Ch08 (Gap analysis)

---

doc/ref_arch/openstack/chapters/chapter03.md

3.1 moved sentence “Please note that while requirements are provided in various sections of this chapter for traceability, the source of record is Chapter 2.” to 3.6. 
3.4.2. Physical Infrastructure: deleted comment "content to be developed", reworded a sentence, deleted the two sub-bullets under "Storage" and added a link to RA-1 Ch04 Storage section
3.4.2.2. Deleted memory jogs for content; corrected "... TOR (C/Agg-leaf) to "... TOR (Leaf/Access)"
3.4.2.3 Deleted memory jogs for content -- Ceph moved to RA-1 Ch04
Fixes #879

[RA1 Ch03] Update chapter03.md

---

doc/ref_cert/lfn/chapters/chapter03.md
doc/ref_cert/lfn/chapters/chapter04.md

Clarifying the requirement that test cases muyst support some means of
running in an internal enterprise lab environment.
Moving empty sections for listing performance, resilience and bare-metal
validation test cases to chapter 4.
fixes #890 
fixes #891

[RC1 Ch03] Clarifying requirement for offline execution of TCs

---

doc/ref_cert/lfn/chapters/chapter11.md

Port VTP test cases to Xtesting [1] is key because the TC doesn't conform
to the principles and requirements defined.
https://github.com/cntt-n/CNTT/issues/917

[RC1] Fill all gaps already tracked as issues in CNTT

---

doc/ref_model/chapters/chapter04.md

It looks like the write IOPS for bronze was quite out of line with the other metrics.
Has any thought been given to synthetic workload for the disk test?  Is it based on a single thread of I/O waiting for completion?  Or async, with multiple requests in flight?
Also, will there be latency requirements?

[RM Ch04] Update metrics for Storage

---

doc/ref_arch/kubernetes/chapters/chapter02.md

This PR seeks to address #602  and #615  by adding APIs to manage NFVI infra including compute, networking, and storage as a requirement.

[RA2 Ch02] Adding API driven LCM

---

doc/ref_cert/lfn/chapters/chapter01.md

Fixes Issue #1026 .  
Fixing broken glossary/terminology URL 
from:  https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/ref_model/chapters/glossary.md
to:  [CNTT Terminology](../../../ref_model/chapters/glossary.md).

RC-1 Ch01 - Fix broken URL issue 1026

---

doc/ref_arch/kubernetes/chapters/chapter02.md

The former requirement enforces an implementation detail.
The new wording outlines a capability instead of an implementation detail.
If we want this capability to be programmatically configured/controlled via an API, then that should be a separate requirement. Even then, such a requirement should not specifically call for a custom CNI plugin since this is an implementation detail.

[RA-2 Ch02] req.inf.ntw.16 states a capability rather than an implementation detail

---

Gemfile
build.sh

This change adds a build script to build the documentation.
At the moment the script supports only Ubuntu and it is very
rudymentary, but at least a start.
This is the 0th step to fix #1023

Build script of the documentation

---

doc/ref_arch/kubernetes/chapters/chapter04.md

This PR attempts to more clearly specify that the deployment tool used for
RI2 must either be listed as conformant or make use of an installer
which deploys a conformant K8s cluster.
Fixes #1038

Clarify requirement on conformant K8s installer for RI2

---

doc/ref_arch/kubernetes/chapters/chapter08.md

Proposing a template to document gaps and enable traceability back to requirements in RA and RM. This PR addresses Fixes #985.

[RA2] Ch8 - Gap documentation template

---

doc/ref_arch/kubernetes/chapters/chapter02.md

The requirements e.nfvi.res.cap.001, e.nfvi.res.cap.002, and
e.nfvi.res.cap.003 in chapter 2 state maximum values for virtual
CPU, memory and disk sizes. This PR clarifies that those numbers
are not intended as a hard upper limit, but just state that a platform
has to support *at least* those maximum values. The actual maximum
values can be larger in a vendor implementation.
fixes #1068

[RA2 Ch02] Values for virtual CPU, memory, and disk capabilities

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

It updates both RA1 and RC1 according to the traceability in place:
- set as optional a few neutron extensions newer than Pike
- set l3 extensions (linked to reference implementations) as optional
It's being completed by the regex update in Functest both verified via OVS agents and OVN.
Close: #1106

[RA1][RC1] Set Neutron extensions as optional

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Multi-tenancy is an **implementation detail** which Kubernetes has not and likely will not implement. The "multi-tenant" approach in sig-multi-tenancy appears to be focused primarily on nested namespaces and nested CRDs which will likely fall short of the safety requirements and resource restraints which we are seeking.
Instead, we should state the desired goals which consist of at least the following:
1. Security between workloads that are mutually ignorant of each other.
2. Resources must be restrained. A workload must not be capable of starving other workloads of resources unless specified by policy.
A reference implementation may choose to implement multi-tenancy or something else as an isolation and resource management strategy. Furthermore, separating these into two separate goals …

[RA-2 Ch02] Replace multi-tenancy with desired intents

---

doc/ref_cert/lfn/chapters/chapter03.md

It update tempest_slow regex (Neutron) according to the last changes in
CNTT RA1 Chapter5 (l3_agent_scheduler is now optional).
Closes: #1106

[RA1][RC1] Update Regex list in RC

---

doc/ref_arch/kubernetes/chapters/chapter02.md

In Chapter 02, In the section 2.2.2 Network Interface Options, the network interface option link is invalid. Fixed it by pointing to RM - 4.2.2 Virtual Network Interface Specifications

[RA2 CH02] Fix for broken link

---

doc/ref_arch/openstack/chapters/chapter04.md

Fixes #685 
Copy of note from Issue #685 
On the RA-1 Technical Call of Feb 24, 2020, it was decided that the Chapter 4.3.3 "Build Parameters" belongs to RI. RI may include references to generic OSTK and/or vendor specific distributions – will depend upon the operator.

[RA-1 Ch04] Delete 4.3.3. Build Parameters

---

doc/ref_model/chapters/chapter04.md

Fixes #1126 
Section 4.1.4.2 Table 4.6:
-  "CPU overbooking" renamed  "CPU allocatio ratio"
- definition provided " Number of virtual cores per physical core"
- expression of the ratio changed for consistency
Same modifications applied to table 4.24

[RM Ch04] CPU overbooking

---

doc/ref_impl/cntt-ri/chapters/chapter03.md

Fixes #1193
Typo fix - correction only: Section 3.4 infrastrucutre(inf) to "infrastructure"

[RI-1 Ch03] General Doc Cleanup - fix typo

---

doc/ref_arch/kubernetes/chapters/chapter02.md

[RA2 Ch2] Wording to deal with requirements that are optional at deployment time.

---

doc/ref_arch/kubernetes/chapters/chapter02.md

Resolves #614 
All those removed are covered by the two following requirements:
req.gen.cnt.04 | Cloud nativeness | The Architecture must run conformant Kubernetes as defined by the CNCF.
req.int.api.02 | API | The Architecture must leverage the Kubernetes APIs to discover and declaratively manage compute (NFVI and bare metal resources), network, and storage.
The first ensures the Kubernetes used has a CNCF conformant API, and the second ensures all resources are managed through that API.

RA2 Ch2 - remove commented requirements

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

It was not listed in Keystone which defacto sets it as optional.
It may be considered as mandatory in a second step.
It should be noted that it's not working in CNTT RI and there is no
true plan to update CNTT RI from the time writing.
RA1 and RC are updated in one change according to the traceability in
place.

[RA1][RI1][RC1]Add oauth1 as optional Keystone features

---

doc/ref_model/chapters/chapter04.md

Remove two instances of editorial comments about where NFVI profiles are available.
Remove one instance of compute-intensive reference.
Fixes #1255

[RM] remove editorial comments about where NFVI profiles are available.

---

doc/ref_model/chapters/chapter05.md

Make Object storage optional in RM.
Extract Object storage from NFVI profiles to an NFVI platform service.
Fixes #524.

[RM] Make object storage optional in RM

---

doc/ref_model/chapters/chapter04.md

Table 4-17 describes the size of different comput flavors, but in Kubernetes the
CPU and memory size is defined with requests and limits. This change clarifies that
these numbers define resource requests in case of Kubernetes.

[RM Ch04]: Kubernetes related clarification to Table 4-17

---

doc/ref_cert/lfn/chapters/chapter01.md

Fixes #1056 - [RC1 - Ch01] Clarify Conformance Categories (NFVI & VNFs)
See issue for research performed to simplify and standardize Conformance, and separate from Compliance, and avoid Certification.

[RC1 - Ch01] Clarify Conformance Categories

---

doc/ref_arch/kubernetes/chapters/chapter04.md

The NSX Container Plugin (NCP) is a container plugin that integrates with NSX-T Data Center to build Kubernetes networking and security objects. The NCP can also serve as a metaplugin/CNI multiplexer that is capable of attaching multiple interfaces to Kubernetes Pods to provide multiple NIC container support

[RA2 Ch4] updates to include NSX Container plugin(NCP)

---

doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md
doc/ref_arch/openstack/chapters/chapter05.md

Fixes #1411
Cyborg is removed for Baldy RA1 release and will be introduced later on with relevant OpenStack releases.
Modifications applied to Chapter 3, 4 and 5
Chapter 3, Section 3.3.1.3, Cyborg removed from components table

[RA1 Ch03, Ch04, Ch05] Cyborg removed for Baldy

---

doc/ref_cert/lfn/chapters/chapter03.md

It completes the change "Rename CNTT specific testcases" [1].
Test DB and API don't support suites which raise side effects in Cachet
if both IaaS verification and CNTT conformance are executed [2]
Vmtp and Shaker haven't been modified for CNTT. They will be renamed
once CNTT asks for new post processing.
[1] https://gerrit.opnfv.org/gerrit/c/functest/+/69864
[2] http://testresults.opnfv.org:8080/

[RC1] Rename Functest CNTT test cases

---

doc/ref_arch/kubernetes/chapters/chapter04.md

[RA2 Ch4]: Removal of VMware NCP

---

doc/ref_arch/openstack/chapters/chapter03.md
doc/ref_arch/openstack/chapters/chapter04.md

Fixes #1453 
The Barbican OpenStack service described in Chapter5 is not described in Chapter 3 and 4.
Text added in Chapter 3 and 4

[RA1 Ch03 ch04] Barbican description

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

It's not supported by radosgw which includes a different
synchronization model, multisite operations, for users who require
that feature [3].
From an interopability point of view it seems fine to set it as
optional. It should be noted that radosgw is used in both CNTT
reference implementations (Functest [2] and Airship [3]).
[1] https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3.2/html-single/release_notes/index
[2] http://artifacts.opnfv.org/functest/E46RCZLBRYCC/functest-opnfv-functest-smoke-hunter-tempest_slow-run-127/tempest_slow/tempest-report.html
[3] http://artifacts.opnfv.org/cntt/WKFRPQODPW34/cntt-opnfv-functest-smoke-latest-tempest_slow-run-37/tempest_slow/tempest-report.html

[RA1][RC1] Set Swift container_sync as optional

---

doc/ref_model/chapters/chapter06.md

NFVI, VIM and VNF was removed from the parts of the text which is not
explicitly about the ETSI NFV architecture.
I think we should not remove the ETSI NFV terminology from the parts where they are used int the ETSI NFV context. 
Partially closes #1168

[RM Ch6]: Partial removal of NFVI, VIM and VNF

---

doc/ref_cert/lfn/chapters/chapter03.md

Horizon is mandatory in CNTT and then must be covered by Functest
tempest_horizon.
The test was backported to Hunter [1] and then must be listed in RC
and executed into RI.
[1] https://gerrit.opnfv.org/gerrit/c/functest/+/69932
Closes #1472

[RC1] Add Horizon testing in CNTT RC1

---

doc/ref_arch/kubernetes/chapters/appendix-a.md

#1537 changes the title of Appendix A of the Reference Model. The RA2 Appendix contains a reference to the RM Appendix, hence the correction.

[RA2 Appendix A] Correcting reference to the RM Appendix

---

doc/ref_model/README.md

#1537 changes the title of Appendix A of the Reference Model. The ReadMe contains a reference to the RM Appendix, hence the correction.

[ReadMe] Correcting reference to the RM appendix

---

doc/ref_cert/lfn/chapters/chapter04.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

It duplicated tempest_neutron and then were removed.
It follow the upstream changes in Functest.

[RI1][RC1] Remove neutron_trunk refs

---

doc/ref_cert/lfn/chapters/chapter03.md

Octavia is optional from the time being.
It has to be over protected even if tempest config may apply
the exclusion.

[RC1] Exclude Octavia testing in tempest_heat

---

doc/ref_impl/cntt-ri/chapters/chapter06.md

Based on the feedback, most installers except one is not interested to support another format of descript files beyongs its own native format. The one that supports PDF incurred loss of functionality. Openstack Airship community also has no interest to support PDF. The estimate from Sridhar to implement such conversion tool is 3 developers/2months for the initial implementation based on Airship Treasuremap 1.7, then needs a redo when AS 2.0 is released late this year. PDF/IDF also needs to be drastically expanded to support the Airship supported configurations. So after discussion with Sridhar and Al, I am proposing to change this requirement from "must" to "may".

[RI-1 Ch06] Change the requirement level from must to may in req.gen.ins.01

---

doc/ref_cert/lfn/chapters/chapter03.md

Linked to req.inf.ntw.16 [1]
The Architecture must support dual stack IPv4 and IPv6 for tenant
networks and workloads
Closes #1556
[1] https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter02.md

[RC] Enable test_network_v6 (linked to req.inf.ntw.16)

---

doc/ref_cert/lfn/chapters/chapter03.md

RA1 chapter5 select Pike's microversions and then a few tests should have been skipped in CNTT.
It's linked to https://gerrit.opnfv.org/gerrit/c/functest/+/70186

[RC1] Blacklist tempest tests newer than Nova microversion 2.53

---

doc/ref_cert/lfn/chapters/chapter02.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

CNTT RC1 was restructured and then it completes the previous PR.
Fixes #1406

[RC1] Fix obsolete refs to RC1 chapter09

---

doc/ref_arch/openstack/chapters/chapter05.md

The data is missing and it's currently verified by CNTT RC.
enable_instance_password is set to true as default value in both
Nova [1] and Tempest configurations [2].
It must be cherry-picked to Baldy to sync RA1 and RC1.
[1] https://docs.openstack.org/nova/pike/configuration/config.html
[2] https://docs.openstack.org/tempest/latest/sampleconf.html
Fixes #1608
(cherry picked from commit 0211c1e73fcae25861a1d96f258e781494f6cfc1)

[RA1] Add instance_password in Nova capabilities

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

As detected by Orange's RC Field trial, Ceph doesn't support this
feature before Rocky [1].
"AttributeError: 'RBDDriver' object has no attribute 'unmanage_snapshot'"
manage_snapshot testing is fully passing in Functest SUT because CNTT
is verified vs OpenStack Rocky and newer.
Ceph is selected by RI as backend and is widely reused by the ecosystem.
It's similar to [2].
manage_snapshot will be mandatory back once CNTT selects Rocky or newer.
[1] https://bugs.launchpad.net/cinder/+bug/1645288
[2] https://gerrit.opnfv.org/gerrit/c/functest/+/69888

[RA1]RC1] Skip manage_snapshot in CNTT

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

As detected by Orange's RC Field trial, Ceph doesn't support this
feature before Rocky [1].
"AttributeError: 'RBDDriver' object has no attribute 'unmanage_snapshot'"
manage_snapshot testing is fully passing in Functest SUT because CNTT
is verified vs OpenStack Rocky and newer.
Ceph is selected by RI as backend and is widely reused by the ecosystem.
It's similar to [2].
manage_snapshot will be mandatory back once CNTT selects Rocky or newer.
[1] https://bugs.launchpad.net/cinder/+bug/1645288
[2] https://gerrit.opnfv.org/gerrit/c/functest/+/69888
(cherry picked from commit 181b5f038efd06e85b568807c7ab73119bfb631b)

[RA1][RC1] Skip manage_snapshot in CNTT

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md

Reverts cntt-n/CNTT#1628
Approved without having WSL approval. 
I suggest to discuss in upcoming RA-1 call.

Revert "[RA1]RC1] Skip manage_snapshot in CNTT"

---

doc/ref_arch/openstack/chapters/chapter05.md

The microversions specified are the maximal versions for Pike -- correcting typo ("minimal")
Fixes #1586

[RA-1 Ch05] Change to "Maximal API microversion"

---

doc/ref_cert/lfn/chapters/chapter03.md

Trusts redelegation is supported by Train [1][2] which forces to skip
RemoteStack as CNTT Baldy is designed for Pike (the support is
incomplete in case of trust [3]).
It will be enabled back once CNTT selects Train or newer.
[1] https://docs.openstack.org/releasenotes/heat/train.html#relnotes-13-0-0-stable-train
[2] https://github.com/openstack/heat/commit/e377658586c737150dad1bfd80b7b2267d46be51
[3] https://bugs.launchpad.net/heat/+bug/1701498

[RC1] Remove RemoteStack testing from tempest_heat_cntt

---

doc/ref_model/chapters/chapter05.md

Replaced "content to be developed" by "Please see the [RM Security Chapter](./chapter07.md) and, in particular, the [Consolidated Requirements](./chapter07.md#711-consolidated-security-requirements) section."
Same fix would be performed for Baldy release.
Fixes #1669

[RM Ch05] Section 5.1.4 content

---

doc/ref_cert/lfn/chapters/chapter03.md

Neutron leverages on the upstream Rally task in Stein and newer.
Leveraging on the upstream task fill better the CNTT model.
Then it stops leveraging on specific neutron plugins and extra.
[1] https://build.opnfv.org/ci/view/functest/job/functest-hunter-daily/574/
(cherry picked from commit 00f5f8b7766672c433e535e9801b16caed29531e)

[RC1] Select upstream create_and_list_trunks

---

doc/ref_arch/openstack/chapters/chapter02.md

Fixes #1707 
Traceability for Security requirements section: links added to the content matching the requirement, sub-sections: 2.3.8.1, 2.3.8.5, 2.3.8.7
+ Change on description and relative links for section 2.3.8.2 to homogenize the formats

[RA-1 Ch02] Security requirements: Add links to traceability

---

doc/ref_cert/README.md
doc/ref_cert/lfn/chapters/chapter02.md
doc/ref_cert/lfn/chapters/chapter04.md

All CNTT conformance suites fulfill to the next couple of test case integration
requirements to guarantee a smooth overall integration, the same end user
actions and a unique test result format (e.g. OPNFV test database) needed by
the end users and the test case result verification programs (e.g.
[OVP](https://www.opnfv.org/verification)). Historically, these rules were
agreed by RC1 team and have been applied since
[CNTT Snezka](https://github.com/cntt-n/CNTT/wiki/Snezka). The new RC2 stream
asks to move them in this common place applicable to all CNTT conformance
suites.

[RC1][RC2] Move test case integration requirements to a common place

---

doc/ref_model/chapters/appendix-a.md

The readthedocs compilation toolchain does not compile tables with tabs,
therefore the exception table is reformatted not to have tabs.
Also the not used rows are deleted.

[RM Appendix]: Correcting exception table formatting

---

doc/ref_cert/lfn/chapters/chapter02.md
doc/ref_cert/lfn/chapters/chapter03.md
doc/ref_cert/lfn/chapters/chapter04.md

It backports the mistakes detected when reviewing the test case
integration requirements [1]
[1] https://github.com/cntt-n/CNTT/pull/1725

[RC1] Fix english mistakes (backport)

---

doc/ref_model/chapters/chapter07.md

Fixes #1758 
Tables modifications in section 7.11 :
"Unit" column removed 
"Definition" column replaced by "Definition/Note"
To be consistent with the convention adopted within RA1 for requirements reference, the prefix "req" is added

[RM Ch07] Securiry requirements: tables modifs

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/lfn/chapters/chapter03.md
doc/ref_cert/lfn/chapters/chapter08.md

- add the Functest branch in all links
- remove neutron version which is now useless
- remove ocata from all refs
- rename subnetpool_prefix_ops to subnetpool-prefix-ops
- remove the false test_volume_migrate_attached

[RC1][RA1] Backport a couple of key fixes from master

---

doc/common/README.md

Having all content in H1 chapters makes the generated ToC in readthedocs "unbalanced".

[GOV common]: Moving content to H2 chapters

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/RC1/chapters/chapter03.md

It updates microversions and links according to Train.
It should be noted that the last hot version is 2018-08-31 (rocky).

[RA1] Update Chapter 5 to Train

---

doc/common/abbreviations.md

Fixes #1803 
List of abbreviations of terms used in the Common and README documents.
PS although CNI is a Kuberntes related terms and used more in RA-2, it is sued without explanation in a "common" document

[TSC Common] Common Abbreviations

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/RC1/chapters/chapter03.md
doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC1/chapters/chapter08.md

It updates all links, all Functest docker tags (Jerma), and all test
framework verisons according to Train.
It adds tempest_horizon which was missing in the manadatory test case
list (it's being backported to baldy).

[RC1] Update links, test case descriptions and selections to Train

---

doc/ref_model/chapters/chapter07.md

Fixes #1506 and #1508
Per the comment from issues1506 and 1508, we can not completely prohibit root login, but restrict root login only when it is mandatory.
Modifications made to 7.5.1.2 and 7.5.2 and addition made to req.sec.gen.006

[RM Ch07] Secure Logging, root login

---

doc/ref_arch/openstack/chapters/chapter02.md

As per Meeting of July 27, 2020, the three SDN requirements in RA-1 2.4.2 are being commented out. These will be replaced as and when RM defines the SDN requirements.
Fixes #1075

[RA-1 Ch04] Comment out SDN Requirements

---

doc/ref_model/chapters/chapter07.md

Fixes #1841 
Proposal to make the chapter more consistent
I kept almost all the content and I restructured the sections:
- text moved to the introduction 
- section' Potential attack vectors' moved after the introduction
- section 7.9.6 'Cloud infrastructure & cloud infrastructure manager" deleted: content alredy covered before
- 'Common security standard' and 'Testing' moved after requirements

[RM Ch07] Restructuring sections 7.3 to 7.10

---

doc/ref_model/chapters/chapter04.md

Fixes #1848 
Table 4-15 caption changed from "Storage Performance Profiles" to "Storage Extensions" as per discussion in RM meeting of July 29, 2020.
Also need to be changed in Baldy

[RM Ch04] Table 4-12 Caption Correction

---

doc/ref_model/chapters/chapter07.md

Fixes #1881 
7.3.1 Alignment with terminology of chapter 3, ETSI figure removed (no longer in chapter 1)
"Platform" replaced by "Cloud Infrastructure" when possible
Merge of 'Platform Patching"section content within General security requirements
Merge of Software "Encryption, Password and Banner" content within Software Hardening
7.5.7 Identity and Access Mangament: empty section, removed
7.6 Workload security- Operator Responsability ->Workload security- Cloud Infrastructure Operator Responsability
7.7 Application vendor responsability, redundant content, section removed
Merge of content of "Cloud infra vendors and cloud infra manager vendors" ->Workload security- Cloud Infrastructure Operator Responsability

[RM Ch07] Clean up: sections 7.3 to 7.8

---

doc/ref_arch/kubernetes/chapters/chapter04.md

Moving the original content of Chapter 4.5 to the new structure. 
closes #1637

[RA2 Ch4]: Reinstate Chapter 4.5 content in new format

---

doc/ref_impl/cntt-ri/chapters/chapter09.md

The referred image no longer exist.

[RI1 Ch9]: Removal of broken image link from 9.2.1 Pharos Specification

---

doc/ref_model/chapters/chapter04.md

Updated Table 4-17 and some contents in Sec 4.2.7.3 on forward compatibility removing technology specific aspects as per the alignment with Pr #1917 and #1922 around hardware accelerations

[RM Ch04] Table 4-17 and forward compatibility updates

---

doc/ref_model/chapters/chapter10.md

In [RM Chapter10](https://github.com/cntt-n/CNTT/edit/master/doc/ref_model/chapters/chapter10.md) there are not links from TOC to Challenges and Gaps text.
Fixes #1941 .

[RM Ch10] Add TOC links for Challenges and Gaps text

---

doc/ref_model/chapters/chapter04.md

Fixing link in 4.2.7.3 Forward compatibility to Ch9 4.3 Transition Framework.
Fixes #1953 .

[RM Ch4] Fixing link in 4.2.7.3 Forward compatibility

---

doc/ref_cert/RC2/chapters/chapter03.md

It allows benchmarking Kubernetes API via the scenarios proposed by
xrally_kubernetes integrated as xrally_kubernetes_full by Functest.
The test case traceability to requirement is abstract because there
have been no specific CNTT requirement for benchmarking mainline
API calls yet.
It will be completed by next commits which will add:
- API testing
- Security testing
- Opensource CNF onboarding and testing
Closes #1745

[RC2] Describe and select Kubernetes API benchmarking

---

doc/ref_model/chapters/chapter07.md

Fixes #1755 
Section  7.9.1 and 7.9.3, 
the note 'this requirement’s verification goes beyond CNTT testing scope' was added  for the following requirements: 
req.sec.gen012 - The Operator **must** ensure that only authorized actors have physical access to the underlying infrastructure.
req.sec.wl.005 - Production workloads **must** be separated from non-production workloads

[RM Ch07] Requirements not verifiable

---

doc/ref_model/chapters/chapter10.md

I made it clear that Octavia is a backwards compatible replacement of LBaaS API

[RM Ch 10.3 Load Balancing]

---

README.md
doc/ref_cert/RC2/chapters/chapter04.md

It leverage on Xtesting CI and the playbook published in Functest [1].
It runs all CNTT RC2 mandatory test cases [2].
[1] https://git.opnfv.org/functest-kubernetes/commit/?h=stable/kali&id=51c2e933b06cd0bbbdd825ba25d3d46040f4d452
[2] https://github.com/cntt-n/CNTT/commit/6af033c254727b7405fbfb2efbaa023e2b8ba876

[RC2] Publish CNTT RC2 Cookbook

---

doc/ref_cert/RC2/chapters/chapter03.md

Else it would falsy assume that it's an all-in-one-deployment [1].
[1] https://gerrit.opnfv.org/gerrit/c/functest-kubernetes/+/71109

[RC2] Split kube_bench into kube_bench_master and kube_bench_node

---

doc/ref_cert/RC2/chapters/chapter03.md

Functest Kubernetes offers 2 test cases deploying vIMS via kubectl and
Helm.

[RC2] Slightly update Opensource CNF onboarding and testing

---

doc/ref_cert/RC2/chapters/chapter03.md

The following vulnerability categories tagged as high by kube-hunter
lead to a test case failure:
- RemoteCodeExec
- IdentityTheft
- PrivilegeEscalation
It partially closes #1984

[RC2] Take kube-hunter vulnerability categories into account

---

doc/ref_arch/openstack/chapters/chapter01.md

Fixes #2047 
Section 1.3 Terminology, RA1 terminology section is empty.
OpenStack terminology: addition of the link to Common Glossary OpenStack related Terminology which already exists

[RA1 Ch01] RA1- terminology empty

---

doc/ref_cert/RC2/README.md
doc/ref_impl/cntt-ri/README.md

CNTT RC2 works well and is already in-use in Orange RFP [1].
-alpha is falsy misleading the endusers about its quality.
CNTT RI1 has never been executed in OPNFV since Jun 9, 2020.
The last run deploys OpenStack Ocata which is far from Train as
expected by CNTT RA1 (it should be noted that RI1 was alpha in Baldy
for the same OpenStack version.
[1] http://testresults.opnfv.org/functest/rfp/
(cherry picked from commit 46e19a20f2da36cb2f5cb3b8c93c620573d8b9bd)

[RC2][RI1] Fix CNTT RC2 and RI1 versions

---

doc/ref_arch/kubernetes/chapters/chapter02.md

The commented out `req.inf.ntw.11` breaks the documentation builds in GitHub pages and
on ReadTehDocs, therefore it is removed.
Fixes #2064

[RA2 CH2]: Fix table 2-7

---

doc/ref_arch/openstack/chapters/chapter02.md

Fixes #1976 
Section 2.2.3: the requirements infra.com.cfg.001, 002, 003, 004 are duplicated, already covered in  2.2.1.
They are removed from 2.2.3, section 2.2.3 addressing storage and networking requirements is renamed.
Modifications of 2.2.1 and 2.2.3 titles

[RA1 Ch2] Duplicated requirements

---

doc/ref_arch/kubernetes/chapters/chapter04.md

Partially closes #1911 
As I propose in #1912 the differences between Multus and DANM should be more explained if we would like to allow the usage of both Multiplexers. 
I also think that we should list the gaps of Multus in the gaps chapter.

[RA2 Ch4]: Clarifications of differences between CNI multiplexers

---

doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

It's asked by latest Ansible versions as supported by the main
GNU/Linux distributions (>=2.9).
Please see https://github.com/ansible-collections/community.general

[RI1][RC1][RC2] Get the Ansible collections when calling RC cookbooks.

---

doc/ref_arch/kubernetes/chapters/chapter03.md

Fixes #2140 .
Reorder 3.2.1.x https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter03.md#3.2.1 sections and TOC, so it is sorted by starting with what is always needed (3.2.1.1 Container Runtime Services) and better fits with flow of other parts.

[RA2 Ch3] Reorder 3.2.1.x sections and TOC

---

doc/ref_model/chapters/chapter07.md

Fixes #2159 
Precision added for requirements req.sec.img.002 and req.sec.gen.009 to align with automation's requirements
Wording alignment: VNF replaced by NF or workload

[RM Ch07] Security requirements + Typos

---

doc/ref_model/chapters/chapter09.md

It adds a couple of CI/CD design requirements to allow smoothly deploy
and test the cloud infrastructures and the hosted network functions.

[RM Ch09] Add CI/CD design requirements

---

doc/ref_arch/kubernetes/chapters/chapter03.md

Fixes #2184 .
#2150 had it in but then likely I didn't resolve well some other conflict.

[RA2 Ch3] Move merged Topology text from 3.2.1.2 to 3.2.1.4

---

doc/ref_model/chapters/chapter09.md

In context of CNTT, we must expect CNTT RC1 and RC2 to pass to promote
software or to verify deployment.

Add CNTT RCX as mandatory pipeline steps.

---

doc/ref_model/chapters/chapter05.md

Fixes #2186 
infra.net.cfg.002 should have the same info for Basic as well as Network Intensive; this was present before the Table was edited

[RM Ch05] Fix missing info from Section 5.2.3

---

doc/common/glossary.md

PVP is one of the data-path topologies specified in TST009 for testing data-plane performance. Suggest the terminology section in this glossary either be comprehensive for all terms used in RM/RA/RI/RC ... OR ... to have more general terminology defined here and define/reference narrow terms such as PVP in the relevant Anuket spec (either in the text or in a "sub" glossary).

Remove definition of PVP

---

doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_cert/README.md

It's the last Kubernetes release before the CNTT release.
Functest Leguer is selected now according to k8s v1.20.

Update RC2 to v1.20 and to Functest Leguer

---

doc/common/glossary.md

This pull request is to replace [Glossary] Terminology definition for testing per issue #1495 #1649. Pull request #1649 has been closed as the edited file was moved and therefore could not resolve merge conflicts. The pull request was originally approved by @acmacm @xmulligan @pgoyal01 @tomkivlin

[Glossary] Adding test related terminology

---

doc/ref_cert/RC2/chapters/chapter02.md

It's the conterpart of "[RA2] Add Special Interest Group level
requirements" [1].
The other SIGS will be completed by additional pull requests.
[1] https://github.com/cntt-n/CNTT/pull/2332

[RC2] Add SIG Testing traceability

---

doc/ref_model/chapters/chapter03.md

This PR is to replace PR#2347: "Added 3.4.2 Time Sensitive Workloads" in order to remove the section. numbering conflicts.  The contents is the same.  However, it is proposed to collapse all contents on this topic into just one section (in PR#2347 it was divided into two sections)

[RM 3.5.4] Time Sensitive Networking

---

doc/ref_arch/kubernetes/chapters/chapter03.md

"SmartSwitches" -> "Smart Switches".
fixes #2410

[RA2 Ch3] Fixing typo in 3.2.1.7 Hardware Acceleration

---

doc/ref_model/chapters/chapter04.md

Fixes issue #2352 
Obsolete CNTT policies
In Table 4-2, text mentioning prohibition of features requiring workloads hardware-dependent code has been removed for e.cap.013 to e.cap.016

[RM Ch04] Obsolete CNTT policies 

---

doc/ref_arch/kubernetes/chapters/chapter03.md
doc/ref_arch/kubernetes/chapters/chapter07.md

[Memory Manager](https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/) was added in v1.21 (as alpha feature). Updated [3.2.1.3 Memory and Huge Pages Resources Management](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter03.md#3213-memory-and-huge-pages-resources-management), [3.2.1.4 Hardware Topology Management](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter03.md#3214-hardware-topology-management) and [7.2.8 HW topology aware hugepages](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter07.md#728-hw-topology-aware-hugepages).
Any guidance on alpha-level feature - please let me know.
Closes #2423 .

[RA2 Ch3+Ch7] Add Memory Manager

---

doc/common/README.md

The whole approach chapter was removed as the referred link to the approach document
was broken.
Closes #2437

[Common]: Removal of broken link to approach

---

doc/ref_arch/kubernetes/chapters/chapter06.md

It remains sig-storage which asks for a deep dive on both features
and drivers. As starting point, the features list conforms with the
upstream K8s gates (kind).
It allows RA2 team to update the mandatory choices which RC2 will
conform. It's worth mentioning that a few related test could be still
skipped in RC2 (only for gce, disruptive, alpha, etc.).

[RA2 Ch06] Add most of sigs in RA2 chapter 6

---

doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_cert/README.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

It's now also manadatory in all Debian derivated distributions.
It also removes docker as dependendy (it's installed by the role) and
updates RC2 to leverage K8s stable/v1.21 branch (June release).

[RC1][RC2] Add --system-site-packages in virtualenv calls

---

doc/ref_arch/kubernetes/chapters/chapter06.md

It especially breaks rendering.

[RA2 Ch06] nit: Replace tabs by spaces

---

doc/ref_arch/kubernetes/chapters/chapter07.md
doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_cert/README.md

It also updates all test result urls and 2 outdated tags in
doc/ref_cert/README.md.
The test case list will be updated in a next PR.

[RC2] Update Kubernetes and Functest releases in CNTT RC2

---

doc/ref_arch/kubernetes/chapters/chapter06.md
doc/ref_cert/RC2/chapters/chapter02.md

The test case descritions is now up-to-date with CNTT RC2 gates [1].
[1] https://build.opnfv.org/ci/view/functest-kubernetes/job/functest-kubernetes-v1.21-daily/22/

Update the mandatory RC2 test case list

---

doc/ref_cert/RC1/chapters/chapter03.md
doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/README.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

CNTT selects Wallaby for L-release.
It updates all refs to Functest except those in RI1 gate description
(still hunter?) which must be updated by RI1 team according to its
roadmap for L-release.

[RC1] Update to Functest Wallaby

---

doc/ref_cert/RC1/chapters/chapter04.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_impl/cntt-ri/chapters/chapter08.md

It conforms to the update change [1].
[1] https://github.com/ansible-collections/kubernetes.core

[RC1][RC2] community.kubernetes -> kubernetes.core

---

doc/ref_cert/RC2/chapters/chapter02.md

It stops and recreate coredns pods which is incompatible with testing
live env.
An there is no single test in sig_network_serial, it can safely
removed from manatory test cases.

[RC2] Remove DNS configMap nameserver testing

---

doc/ref_arch/kubernetes/chapters/chapter02.md

req.int.api.03 was used twice in chapter02. This change removes
the duplicate.
Fixes: #2584

[RA2 Ch2]: Fixing duplicate requirement id

---

doc/ref_arch/kubernetes/README.md
doc/ref_arch/kubernetes/chapters/chapter07.md
doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_cert/README.md

CNTT RA2 follows the latest stable release.
It also takes into account the new Functest Kubernetes release [1]
[1] https://lists.anuket.io/g/anuket-tsc/message/517

[RA2][RC2] Update to K8s v1.22

---

doc/ref_arch/openstack/chapters/chapter05.md
doc/ref_cert/RC1/chapters/chapter03.md

It updates versions and microversions and takes into account latest
features (disabled by default):
- Neutron
- rbac-address-scope
- rbac-subnetpool
- tag-ports-during-bulk-creation
- Nova
- shelve_migrate
- stable_rescue
- xenapi_apis
- Keystone
- access_rules
- Glance
- import_image
- os_glance_reserved
- web-download import
-Cinder
- extend_attached_encrypted_volume
It also updates all regexes in RC1/Functest.

[RA1][RC1] Update mandatory extensions

---

doc/ref_arch/kubernetes/chapters/chapter04.md

closes #2275
I've added a spec for an IPAM CNI for secondary network interfaces, highlighting it's for all nodes of the cluster (otherwise static or host-local would be ok)
I don't think we need another one for primary interfaces as they're managed by k8s natively.
what about an external dhcp? would that be ok?

[RA2 Ch4] add spec for ipam cni

---

doc/ref_model/chapters/chapter03.md

After consideration, I realised that the Storage Principles have a lot of value of their own, and are very specifically formulated to drive the Storage related requirements. Hence, I propose to leave them in the Storage Section, as they are, but adding a reference to overarching Principles.  In my view, the Storage Principles should be understood as specialisations of overall principles.

[RM Ch03.6] Storage principles

---

doc/ref_cert/RC2/README.md
doc/ref_cert/RC2/chapters/chapter01.md
doc/ref_cert/RC2/chapters/chapter02.md
doc/ref_cert/RC2/chapters/chapter03.md
doc/ref_cert/RC2/chapters/chapter04.md
doc/ref_cert/RC2/chapters/chapter05.md
doc/ref_cert/RC2/chapters/chapter06.md

It cleans the markdown files before we merge all rst.

[RC2] Remove all bogometers in RC2

---

doc/ref_cert/RC2/README.rst
doc/ref_cert/RC2/conf.py

It allows browsing our doc via Github as CNTT actors may do.

Symlink README.rst to index.rst

---

doc/ref_cert/RC2/chapters/chapter02.rst
doc/ref_cert/RC2/chapters/chapter04.rst
doc/ref_cert/RC2/conf.py

It leverages intersphinx [1] and doc role [2] to avoid hardcoding urls.
It remains one case in chapter04.rst which could be removed once CNTT
leverages autosectionlabel.
[1] https://docs.readthedocs.io/en/stable/guides/intersphinx.html
[2] https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-doc-role

[RC2] Leverage the doc role as proposed by Sphinx

---

doc/ref_cert/RC1/chapters/chapter01.rst
doc/ref_cert/RC1/chapters/chapter02.rst
doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/chapters/chapter05.rst
doc/ref_cert/RC1/chapters/chapter08.rst
doc/ref_cert/RC1/conf.py

It leverages intersphinx [1] and doc role [2] to avoid hardcoding urls.
It remains several cases in chapter01.rst and chapter02.rst which could
be removed once CNTT leverages autosectionlabel.
[1] https://docs.readthedocs.io/en/stable/guides/intersphinx.html
[2] https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-doc-role

[RC1] Leverage the doc role as proposed by Sphinx

---

doc/ref_cert/RC2/chapters/chapter02.rst
doc/ref_cert/RC2/chapters/chapter03.rst

It follows the new Kubernetes [1] and Functest Kubernetes releases.
It defacto skips the new features which have not been selected in RA2 yet:
-  [Feature:CustomResourceValidationExpressions]
-  [Feature:StatefulSetAutoDeletePVC]
-  [Feature:GRPCContainerProbe]
[1] https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/

[RC2] Update to Kubernetes v1.23

---

doc/ref_cert/RC1/chapters/chapter03.rst

It fixes cinder "update_volume_type() got an unexpected keyword [1]
and the bugs detected by CI (here Cinder v3) [2].
Also see the related Functest update [3]
[1] https://github.com/openstack/rally-openstack/commit/38ab09ccbe9cea02fe7230a2580dfc8d64503662
[2] https://github.com/openstack/rally-openstack/commit/db87d7f218555f41cc743f249e7ba02b353f0a09
[3] https://github.com/opnfv/functest/commit/a0f54a3fc05ce4dd104181874bf7569607af3064

[RC1] Update Rally OpenStack version

---

doc/ref_cert/RC2/chapters/chapter01.rst
doc/ref_cert/RC2/chapters/chapter02.rst

* Minor typos and spelling corrections.
* Removed "blacklist" in favor of "excludes."
Signed-off-by: Lincoln Lavoie <lylavoie@iol.unh.edu>

Couple of minor typos in the RC2 documentation.

---

doc/ref_cert/RC1/chapters/chapter07.rst

It breaks the full Anuket verification gates.
(cherry picked from commit b0980c5b10e9cda2ec3dfb45494866edc516670e)

[RC1] Update VTP snapshots

---

doc/ref_model/conf.py

Added numfig = True
This will enable Figure numbering.
Here is a suggested use for the Figure 1-1 
LIne 54: within the text use :numref:`Fig-1-1` and the Figure block as:
.. _Fig-1-1:
.. image:: ../figures/ch01_scope.png
:alt: "Scope of Reference Model"
Scope of Reference Model
@collivier @gkunz Can you confirm? Thanks

[RM Ch] conf.py add numfig

---

doc/ref_impl/README.md
doc/ref_impl/README.rst
doc/ref_impl/cntt-ri/index.rst
doc/ref_impl/cntt-ri2/index.rst
doc/ref_impl/index.rst

Now that both RI1 and RI2 are rst based, we can link both pieces
together using proper rst directives. This also enables numbering
of RI1 headings.
Fixes #2873
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

[RI1][RI2] Correctly link RI1 and RI2 from common index

---

doc/ref_arch/kubernetes/README.rst
doc/ref_arch/kubernetes/chapters/chapter06.rst

This change updates the required Kubernetes version to 1.23.
Closes: #2509

[RA2]: Update Kubernetes to 1.23

---

doc/ref_cert/RC1/chapters/chapter08.rst

These gaps are only about RI1 and shouldn't be part of RC1.
As the links are dead since Airship removal, we do clean
this obsolete and falsy content.

Remove automation gaps in RC1 Chapter 8

---

doc/conf.py
test-requirements.txt

Please note that all RTD projects created before Oct 20 2020
must set bounds to enforce a compatible Sphinx version
(see manual).
It also sets autosectionlabel_maxdepth = 4 needed by RA1 and
removes the falsy intersphinx mapping.

[GLOBAL] Fix requirements in gates

---

doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/conf.py
doc/ref_cert/RC2/conf.py
doc/ref_cert/conf.py

It removes duplicates in chapter3 and enforces
all local builds to generate labels to title4.
This global work is needed for RA1.

[RC1] Make title4 uniq

---

doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/chapters/chapter08.rst
doc/ref_arch/openstack/tox.ini

It's only about wrapping long lines and removing
blank chars. Then it allows running doc8 in gates.

[RA1] Fix doc8 issues in RA1

---

doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/conf.py
doc/ref_arch/openstack/tox.ini

It fixes the latest urls and enable linkcheck via tox.
Linkcheck ignores [1] and [2].
[1] https://www.cisecurity.org/cis-benchmarks/
[2] https://www.iso.org/obp/ui/

[RA1] Enable linkcheck

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/chapters/chapter06.rst

fixing build errors
./chapters/chapter03.rst:614: D000 Malformed table.
Multiple head/body row separators (table lines 3 and 8); only one allowed.
D002 Trailing whitespace
D000 Inline emphasis start-string without end-string.
D000 Inline interpreted text or phrase reference start-string without end-string
fix double colon in link:
`/home/opnfv/slave_root/workspace/cntt-tox-ra2/doc/ref_arch/kubernetes/chapters/chapter02.rst:447:undefined label: ref_model/chapters/chapter08:chapter 8 hybrid multi-cloud: data centre to edge
ERROR: InvocationError for command /home/opnfv/slave_root/workspace/cntt-tox-ra2/doc/ref_arch/kubernetes/.tox/docs/bin/sphinx-build -W -b html . build (exited with code 2)
`

[ra2 ch3] fix build errors

---

doc/ref_model/chapters/chapter07.rst
doc/ref_model/chapters/chapter09.rst

Fixes issue#2841
Review of security standards: Standards not mentioned into text are removed
The 'security references' section is removed, references added to 'common security standards'
Links to sections added, manual numbering removed
Some typos correction

[RM Ch07] Review of security standards

---

doc/conf.py
doc/ref_arch/openstack/conf.py
doc/ref_cert/RC1/conf.py
doc/ref_impl/cntt-ri/conf.py
doc/ref_impl/cntt-ri2/conf.py

They are several differences in Sphinx config which breaks
user naviguation.
The proposal is, by default, to use default Material values,
and to apply any change to all streams per PR.
It also selects Figure in all captions (default is Fig.).

Unify Sphinx config

---

doc/ref_cert/RC1/chapters/chapter03.rst
doc/ref_cert/RC1/chapters/chapter04.rst
doc/ref_cert/RC2/chapters/chapter03.rst
doc/ref_cert/index.rst

wiki.opnfv.org is now redirected to wiki.anuket.io.
A few former pages which were not copied no longer exists.

[RC] Update all wiki.opnfv.org links

---

doc/ref_impl/cntt-ri/chapters/chapter01.rst

It fails due to the new redirect.

[RI1] Fix former wiki.opnfv.org links

---

doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter05.rst
doc/ref_arch/openstack/chapters/chapter06.rst
doc/ref_arch/openstack/chapters/chapter07.rst

It recalculates all tab widths to avoid overfulling.
It also removes Windows style chars and manually handle '/' to eases reading.
It also wraps a few lines to 80 chars.

[RA1] Stop overfulling cells and tables

---

doc/ref_arch/openstack/chapters/chapter01.rst
doc/ref_arch/openstack/chapters/chapter02.rst
doc/ref_arch/openstack/chapters/chapter03.rst
doc/ref_arch/openstack/chapters/chapter04.rst
doc/ref_arch/openstack/chapters/chapter05.rst
doc/ref_arch/openstack/chapters/chapter06.rst
doc/ref_arch/openstack/chapters/chapter07.rst
doc/ref_arch/openstack/conf.py
doc/ref_arch/openstack/tox.ini

It stops wrapping ref to ease dynamically change
in the single rst for GSMA document.
It must be noted they are lots of duplicated
label (titles) in ra1.
It also fixes a few issues added by the latest
merges.
run tox -e gsma to get ra1.docx

Allow generating docx for GSMA

---

doc/ref_arch/openstack/refs.bib

The second one is falsy interpreted as part of title.
It may become a big issue if we dynamically convert them
to rst for GSMA docx.

[RA1] Remove duplicated {{ and }} in title

---

doc/ref_arch/openstack/chapters/chapter04.rst

It convert Sizing rules tab (chapter04) into a basic table.
It also removes weird chars found during the analysis.

[RA1] Stop corrupting docx generated by pandoc

---

doc/ref_arch/openstack/tox.ini

It also updates py to 3.10 and selects the latest
OpenSTack stable upper constraints.

Add bash in external programs allowed by tox

---

doc/ref_cert/RC2/chapters/chapter02.rst
doc/ref_cert/RC2/chapters/chapter03.rst

It matches the Anuket requirement targeting Kubernetes v1.25 [1] for the Nile release.
This pull request also updates the testing software to cover this particular version (Functest Kubernetes, kuke-hunter, kube-bench, etc.).
It updates the e2e regexes to make any new feature optional as defined by Anuket rules (RA2 has not changed since moselle).
[1] https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/

[RC2] Update to Kubernetes v1.25

---

doc/ref_model/chapters/chapter09.rst

This is in a partial response to Issue #3088 "Cloud Infrastructure Lifecycle automation; chapter restructure"
Move Telemetry and Observability section to be after Assurance section because these topics are related; improve wording of the opening sentence of the Telemetry and Observability section as suggested by @pgoyal01 
Move Automation discussion to the end of Chapter 9, as this content is somewhat self-contained

[RM Ch09] Automation section moved to chapter end

---

doc/ref_impl/cntt-ri2/conf.py
doc/ref_impl/cntt-ri2/index.rst

Based on the discussion in #3045

[RI2][pcac]: Correcting document title

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

[RA2 Ch4]: Defining the Kubernetes NWPG Network Attachment API as mandatory

---

doc/common/technologies.rst
doc/ref_arch/openstack/chapters/chapter02.rst

Fixes issue #3237
Removal of recommendation Int.acc.02: "The Architecture should not rely on SR-IOV PCI Passthrough for acceleration interface exposed to VNFs" as SR-IOV PCI PT is authorised by inf.acc.03
Typo in inf.acc.03 description corrected

[RA1 Ch02] Removal of recommendation int.acc.02

---

doc/ref_model/refs.bib

url for GSMA FS.40 was missing and is now specified

[RM refs.bib] Specify url for GSMA FS 40

---

doc/ref_arch/openstack/conf.py
doc/ref_arch/openstack/refs.bib
doc/ref_arch/openstack/tox.ini
doc/ref_cert/RC2/chapters/chapter02.rst
doc/ref_cert/RC2/chapters/chapter04.rst
doc/ref_cert/RC2/chapters/chapter05.rst
doc/ref_cert/RC2/conf.py
doc/ref_cert/RC2/tox.ini
doc/ref_cert/tox.ini
doc/ref_impl/cntt-ri/tox.ini
doc/ref_impl/cntt-ri2/tox.ini
doc/ref_model/chapters/chapter07.rst
doc/ref_model/conf.py
doc/ref_model/tox.ini

The certificate has just expired.
It also updates tox.ini to take latest OpenStack stable upper-constraint inito account.
Please note there are other issues in RM which are out of this PR 

Add linkcheck exception for ntia.gov

---

.github/workflows/build-docs.yml
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/conf.py
doc/ref_arch/kubernetes/tox.ini
doc/ref_model/conf.py

This change adds a GitHub workflow to build all documents when a PR is created.
It also adds some fixes needed for a successful build:
- [RM]: Adding ORAN WG4 docs to linkcheck ignore
- [RA2]: Change base python to 3.10
- [RA2]: Use zed upper-constraints
- [RA2 Ch2]: Fixing ntia SBOM link
- [RA2]: Adding https://ntia.gov/page/software-bill-materials to linkcheck ignore

[RM, RA2]: Adding GitHub Workflow and needed fixes

---

doc/ref_model/chapters/chapter04.rst

Fixes #3224 
Added Hugepages metrics to Table 4.8 from ETSI GS NFV-TST 008 V3.5.1 made i.pm.001 and i.pm.003 consistent by removing "clause 6"

[RM] Added Hugepages metrics to Table 4.8

---

doc/conf.py
doc/ref_arch/openstack/conf.py
doc/ref_cert/RC2/conf.py
doc/ref_impl/cntt-ri/conf.py

The OPNFV build servers and the LFN wiki are flaky and cause the GitHub jobs to fail on linkcheck.

[RC1 RA1]: Add OPNFV build servers and the LFN wiki to linkcheck ignore

---

doc/ref_impl/cntt-ri2/chapters/chapter01.rst
doc/ref_impl/cntt-ri2/chapters/chapter02.rst
doc/ref_impl/cntt-ri2/chapters/chapter04.rst

Misclose the last PR and open a new one.
It updates RI2 requirements based on RA2 Nile, and modifies the runbook.

[RI2]: Update runbook and requirements

---

CODEOWNERS

TSC agreed on 2023.08.23 (https://wiki.anuket.io/display/HOME/2023-08-22+TSC+Agenda+and+Minutes) to move the following filed to TSC responsibility:
- GOV folder
- CODEOWNERS
- CONTRIBUTING
- CODE_OF_CONDUCT
- GSMA_CNTT_Terms_of_Reference

[GOV]: Moving governance files to TSC reponsibility

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

fixes #3316 
have added 3 specs for load balancer:
- one for the LB itself and its API
- one for active active via BGP
- one for fast failover / HA - ie to prevent ARP VIPs
may also add:
- session stickiness / persistence
- SCTP
- multihoming / VRF support

[RA2] add LB specs

---

README.rst
doc/common/README.rst
doc/conf.py
doc/gov/chapters/chapter09.rst
doc/index.rst
tox.ini

Removal of archived projects
